import { BadRequestException, Inject, Injectable } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { FINANCIAL_HEALTH_DATABASE, type FinancialHealthDatabasePort } from "./financial-health-database.port.js";
import { FINANCIAL_HEALTH_WEIGHTS, budgetControlScore } from "./financial-health.constants.js";
import type { FinancialHealthDto } from "./dto/financial-health.dto.js";

type Code = keyof typeof FINANCIAL_HEALTH_WEIGHTS;
type Component = { code: Code; weight: number; effectiveWeight: number; score: number | null; weightedScore: string | null; status: "GOOD" | "ATTENTION" | "CRITICAL" | "INSUFFICIENT_DATA"; available: boolean; reason: string | null; metrics: Record<string, string | number | null> };
type Period = { start: Date; end: Date };
const zero = () => new Prisma.Decimal(0);
@Injectable()
export class FinancialHealthService {
  constructor(@Inject(FINANCIAL_HEALTH_DATABASE) private readonly database: FinancialHealthDatabasePort) {}
  async calculate(userId: string, query: FinancialHealthDto) {
    const period = this.period(query); if (!query.currency) { const accounts = await this.database.listCurrencies(userId); return { data: await Promise.all(accounts.map(account => this.one(userId, account.currency, period))) }; }
    return this.one(userId, query.currency, period);
  }
  private async one(userId: string, currency: string, period: Period) {
    const month = new Date(Date.UTC(period.start.getUTCFullYear(), period.start.getUTCMonth(), 1)), nextMonth = new Date(Date.UTC(month.getUTCFullYear(), month.getUTCMonth() + 1, 1));
    const [flow, goals, fund, balance, budgets] = await Promise.all([
      this.database.summarizeFlow(userId, currency, period.start, period.end), this.database.listGoals(userId, currency), this.database.findEmergencyFund(userId, currency), this.database.sumCurrentBalance(userId, currency), this.database.listBudgetLimits(userId, currency, month)
    ]);
    const amount = (type: string) => flow.find(row => row.type === type)?.amount ?? zero(); const income = amount("INCOME"), expenses = amount("EXPENSE"), adjustment = amount("ADJUSTMENT");
    const limits = budgets; const spending = limits.length ? await this.database.summarizeBudgetSpending(userId, currency, month, nextMonth, limits.map(limit => limit.categoryId)) : [];
    const components: Component[] = [this.savings(income, expenses), this.budget(limits, spending), this.emergency(fund === null ? null : { desiredMonths: fund.desiredMonths, essentialMonthlyExpense: fund.essentialMonthlyExpense, goal: { currentAmount: fund.currentAmount } }), this.goal(goals), this.netWorth(balance ?? zero(), income.plus(adjustment).minus(expenses))];
    const available = components.filter(component => component.available); const quality = available.length >= 4 ? "SUFFICIENT" : available.length >= 2 ? "PARTIAL" : "INSUFFICIENT"; const totalWeight = available.reduce((sum, component) => sum + component.weight, 0);
    const normalized = components.map(component => !component.available ? component : { ...component, effectiveWeight: new Prisma.Decimal(component.weight).dividedBy(totalWeight).mul(100).toDecimalPlaces(2).toString(), weightedScore: new Prisma.Decimal(component.score ?? 0).mul(component.weight).dividedBy(totalWeight).toFixed(2) });
    const score = quality === "INSUFFICIENT" ? null : Math.round(available.reduce((sum, component) => sum + (component.score ?? 0) * component.weight, 0) / totalWeight); const classification = score === null ? null : score < 40 ? "CRITICAL" : score < 60 ? "ATTENTION" : score < 85 ? "GOOD" : "EXCELLENT";
    const positives = normalized.filter(component => component.available && (component.score ?? 0) >= 75).map(component => this.factor(component.code === "savingsRate" ? "HIGH_SAVINGS_RATE" : component.code === "budgetControl" ? "BUDGETS_UNDER_CONTROL" : component.code === "emergencyFund" ? "EMERGENCY_FUND_HEALTHY" : component.code === "goalProgress" ? "GOALS_PROGRESSING" : "NET_WORTH_GROWING", component.code));
    const negatives = normalized.filter(component => component.available && (component.score ?? 0) < 50).map(component => this.factor(component.code === "savingsRate" ? "NEGATIVE_CASH_FLOW" : component.code === "budgetControl" ? "BUDGET_EXCEEDED" : component.code === "emergencyFund" ? "NO_EMERGENCY_FUND" : component.code === "goalProgress" ? "GOALS_OVERDUE" : "NET_WORTH_DECLINING", component.code));
    return { period: { startDate: period.start, endDate: period.end, currency }, score, classification, components: normalized, positiveFactors: positives, negativeFactors: negatives, recommendations: [...new Set(negatives.map(factor => factor.code === "NEGATIVE_CASH_FLOW" ? "INCREASE_SAVINGS_RATE" : factor.code === "BUDGET_EXCEEDED" ? "REDUCE_BUDGET_OVERRUN" : factor.code === "NO_EMERGENCY_FUND" ? "BUILD_EMERGENCY_FUND" : factor.code === "GOALS_OVERDUE" ? "REVIEW_OVERDUE_GOALS" : "REVERSE_NET_WORTH_DECLINE"))].map(code => ({ code })), dataQuality: { status: quality, missingComponents: components.filter(component => !component.available).map(component => component.code) } };
  }
  private savings(income: Prisma.Decimal, expenses: Prisma.Decimal): Component { if (income.isZero()) return this.missing("savingsRate", "NO_INCOME"); const rate = income.minus(expenses).dividedBy(income).mul(100); const score = rate.lessThan(0) ? 0 : rate.lessThan(5) ? 20 : rate.lessThan(10) ? 40 : rate.lessThan(20) ? 60 : rate.lessThan(30) ? 80 : 100; return this.component("savingsRate", score, { income: income.toString(), expenses: expenses.toString(), savingsRate: rate.toFixed(2) }); }
  private budget(limits: { categoryId: string; limitAmount: Prisma.Decimal }[], rows: { categoryId: string | null; amount: Prisma.Decimal | null }[]): Component { if (!limits.length) return this.missing("budgetControl", "NO_BUDGET"); const byCategory = new Map(rows.map(row => [row.categoryId, row.amount ?? zero()])); let budgeted = zero(), spent = zero(), alert = 0, exceeded = 0; for (const limit of limits) { const value = byCategory.get(limit.categoryId) ?? zero(); budgeted = budgeted.plus(limit.limitAmount); spent = spent.plus(value); const usage = value.dividedBy(limit.limitAmount).mul(100); if (usage.greaterThanOrEqualTo(100)) exceeded += 1; else if (usage.greaterThanOrEqualTo(80)) alert += 1; } const usage = budgeted.isZero() ? zero() : spent.dividedBy(budgeted).mul(100); return this.component("budgetControl", budgetControlScore(exceeded, alert, usage), { totalBudgeted: budgeted.toString(), totalSpent: spent.toString(), totalRemaining: budgeted.minus(spent).toString(), usagePercentage: usage.toFixed(2), normalCount: limits.length - alert - exceeded, alertCount: alert, exceededCount: exceeded }); }
  private emergency(fund: { desiredMonths: number; essentialMonthlyExpense: Prisma.Decimal | null; goal: { currentAmount: Prisma.Decimal } } | null): Component { if (!fund || !fund.essentialMonthlyExpense || fund.essentialMonthlyExpense.isZero()) return this.missing("emergencyFund", "NO_EMERGENCY_FUND"); const months = fund.goal.currentAmount.dividedBy(fund.essentialMonthlyExpense); return this.component("emergencyFund", months.lessThan(1) ? 20 : months.lessThan(2) ? 40 : months.lessThan(3) ? 60 : months.lessThan(6) ? 80 : 100, { coverageMonths: months.toFixed(2), desiredMonths: fund.desiredMonths }); }
  private goal(goals: { targetAmount: Prisma.Decimal; currentAmount: Prisma.Decimal; targetDate: Date | null }[]): Component { if (!goals.length) return this.missing("goalProgress", "NO_ACTIVE_GOALS"); const progress = goals.reduce((sum, goal) => sum.plus(goal.currentAmount.dividedBy(goal.targetAmount).mul(100)), zero()).dividedBy(goals.length); const overdue = goals.filter(goal => goal.targetDate !== null && goal.targetDate < new Date()).length; return this.component("goalProgress", Math.min(100, Number.parseInt(progress.toFixed(0), 10)), { progressPercentage: progress.toFixed(2), activeGoals: goals.length, overdueGoals: overdue }); }
  private netWorth(current: Prisma.Decimal, impact: Prisma.Decimal): Component { if (current.isZero() && impact.isZero()) return this.missing("netWorthTrend", "NO_NET_WORTH_DATA"); const initial = current.minus(impact); if (initial.isZero()) return this.component("netWorthTrend", impact.greaterThan(0) ? 100 : impact.lessThan(0) ? 0 : 50, { currentNetWorth: current.toString(), initialNetWorth: initial.toString(), netImpact: impact.toString(), variationPercentage: null }); const variation = current.minus(initial).dividedBy(initial.abs()).mul(100); const score = variation.lessThanOrEqualTo(-10) ? 0 : variation.lessThanOrEqualTo(-2) ? 25 : variation.lessThanOrEqualTo(2) ? 50 : variation.lessThanOrEqualTo(10) ? 75 : 100; return this.component("netWorthTrend", score, { currentNetWorth: current.toString(), initialNetWorth: initial.toString(), netImpact: impact.toString(), variationPercentage: variation.toFixed(2) }); }
  private component(code: Code, score: number, metrics: Record<string, string | number | null>): Component { return { code, weight: FINANCIAL_HEALTH_WEIGHTS[code], effectiveWeight: 0, score, weightedScore: null, status: score >= 75 ? "GOOD" : score >= 50 ? "ATTENTION" : "CRITICAL", available: true, reason: null, metrics }; }
  private missing(code: Code, reason: string): Component { return { code, weight: FINANCIAL_HEALTH_WEIGHTS[code], effectiveWeight: 0, score: null, weightedScore: null, status: "INSUFFICIENT_DATA", available: false, reason, metrics: {} }; }
  private factor(code: string, component: Code) { return { code, component, severity: "MEDIUM" }; }
  private period(query: FinancialHealthDto): Period { const now = new Date(), start = query.startDate ? new Date(query.startDate) : new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)), end = query.endDate ? new Date(query.endDate) : new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 0, 23, 59, 59, 999)); if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime()) || end < start) throw new BadRequestException({ code: "INVALID_DATE_RANGE", message: "Invalid date range" }); return { start, end }; }
}
