import { Injectable } from "@nestjs/common";
import { FinancialInsightSeverity, FinancialInsightType, Prisma } from "@prisma/client";
import { BUDGET_APPROACHING_LIMIT_PERCENTAGE, BUDGET_CRITICAL_PERCENTAGE } from "../insights.constants.js";
import { detected, percentage, type DetectedInsight, type InsightDetectionContext, type InsightDetector } from "./insight-detector.interface.js";
@Injectable() export class BudgetInsightsDetector implements InsightDetector {
  readonly id="BUDGET"; readonly supportedTypes=[FinancialInsightType.BUDGET_RISK] as const;
  async detect(context:InsightDetectionContext):Promise<readonly DetectedInsight[]>{await Promise.resolve();const results:DetectedInsight[]=[];const exceeded:typeof context.budgets[number][]=[];for(const budget of context.budgets.filter(item=>item.active&&item.currency===context.currency)){const usage=percentage(budget.spent,budget.limit);if(usage===null)continue;const common={budgetId:budget.budgetId,categoryId:budget.categoryId,usagePercentage:usage.toFixed(2),limitAmount:budget.limit.toString(),spentAmount:budget.spent.toString(),currency:context.currency,month:context.period.start.getUTCMonth()+1,year:context.period.start.getUTCFullYear()};if(usage.greaterThanOrEqualTo(100)){exceeded.push(budget);results.push(detected(context,{code:"BUDGET_EXCEEDED",type:FinancialInsightType.BUDGET_RISK,severity:usage.greaterThanOrEqualTo(BUDGET_CRITICAL_PERCENTAGE)?FinancialInsightSeverity.CRITICAL:FinancialInsightSeverity.WARNING,title:"Budget limit exceeded",message:"A category budget exceeded its limit.",metadata:{...common,exceededAmount:budget.spent.minus(budget.limit).toString()},relatedEntityType:"budget",relatedEntityId:budget.budgetId}));}else if(usage.greaterThanOrEqualTo(BUDGET_APPROACHING_LIMIT_PERCENTAGE)){results.push(detected(context,{code:"BUDGET_APPROACHING_LIMIT",type:FinancialInsightType.BUDGET_RISK,severity:FinancialInsightSeverity.WARNING,title:"Budget approaching limit",message:"A category budget is approaching its limit.",metadata:{...common,remainingAmount:budget.limit.minus(budget.spent).toString()},relatedEntityType:"budget",relatedEntityId:budget.budgetId}));}}
  if(exceeded.length>=2){const total=exceeded.reduce((sum,item)=>sum.plus(item.spent.minus(item.limit)),new Prisma.Decimal(0));results.push(detected(context,{code:"MULTIPLE_BUDGETS_EXCEEDED",type:FinancialInsightType.BUDGET_RISK,severity:FinancialInsightSeverity.CRITICAL,title:"Multiple budgets exceeded",message:"Multiple category budgets exceeded their limits.",metadata:{exceededCount:exceeded.length,budgetIds:exceeded.slice(0,10).map(item=>item.budgetId),totalExceededAmount:total.toString(),currency:context.currency,month:context.period.start.getUTCMonth()+1,year:context.period.start.getUTCFullYear()},relatedEntityType:null,relatedEntityId:null}));}return results;}
}
