-- Atlas Finance AI - Recommended Row Level Security (RLS) policies
-- Status: NOT APPLIED.
--
-- These policies are intentionally documentation-only for now.
-- Do not execute this file until the backend is ready to set an application
-- tenant context for every database transaction.
--
-- Project assumptions:
-- - Authentication is managed by NestJS, not Supabase Auth.
-- - Supabase Auth, auth.uid(), auth.jwt(), anon and authenticated roles are not
--   part of the authorization model.
-- - NestJS must set the user context per request/transaction before any query:
--     select set_config('app.current_user_id', '<authenticated-user-uuid>', true);
-- - RLS should only be enabled together with complete policies and tests.
--
-- Optional helper for future activation:
--
-- create or replace function public.app_current_user_id()
-- returns uuid
-- language sql
-- stable
-- as $$
--   select nullif(current_setting('app.current_user_id', true), '')::uuid;
-- $$;

-- ---------------------------------------------------------------------------
-- User
-- Table: public.users
-- ---------------------------------------------------------------------------
--
-- alter table public.users enable row level security;
-- alter table public.users force row level security;
--
-- create policy users_select_own
--   on public.users
--   for select
--   using (
--     id = public.app_current_user_id()
--     and deleted_at is null
--   );
--
-- create policy users_update_own
--   on public.users
--   for update
--   using (
--     id = public.app_current_user_id()
--     and deleted_at is null
--   )
--   with check (
--     id = public.app_current_user_id()
--   );
--
-- User creation, password reset and administrative lifecycle operations should
-- be performed by a trusted backend role, not by public client roles.

-- ---------------------------------------------------------------------------
-- Account
-- Table: public.accounts
-- ---------------------------------------------------------------------------
--
-- alter table public.accounts enable row level security;
-- alter table public.accounts force row level security;
--
-- create policy accounts_select_own
--   on public.accounts
--   for select
--   using (
--     user_id = public.app_current_user_id()
--     and deleted_at is null
--   );
--
-- create policy accounts_insert_own
--   on public.accounts
--   for insert
--   with check (
--     user_id = public.app_current_user_id()
--   );
--
-- create policy accounts_update_own
--   on public.accounts
--   for update
--   using (
--     user_id = public.app_current_user_id()
--     and deleted_at is null
--   )
--   with check (
--     user_id = public.app_current_user_id()
--   );
--
-- create policy accounts_delete_own
--   on public.accounts
--   for delete
--   using (
--     user_id = public.app_current_user_id()
--   );

-- ---------------------------------------------------------------------------
-- Transaction
-- Table: public.transactions
-- ---------------------------------------------------------------------------
--
-- alter table public.transactions enable row level security;
-- alter table public.transactions force row level security;
--
-- create policy transactions_select_own
--   on public.transactions
--   for select
--   using (
--     user_id = public.app_current_user_id()
--     and deleted_at is null
--   );
--
-- create policy transactions_insert_own
--   on public.transactions
--   for insert
--   with check (
--     user_id = public.app_current_user_id()
--     and exists (
--       select 1
--       from public.accounts a
--       where a.id = account_id
--         and a.user_id = public.app_current_user_id()
--         and a.deleted_at is null
--     )
--   );
--
-- create policy transactions_update_own
--   on public.transactions
--   for update
--   using (
--     user_id = public.app_current_user_id()
--     and deleted_at is null
--   )
--   with check (
--     user_id = public.app_current_user_id()
--   );
--
-- create policy transactions_delete_own
--   on public.transactions
--   for delete
--   using (
--     user_id = public.app_current_user_id()
--   );

-- ---------------------------------------------------------------------------
-- Goal
-- Table: public.goals
-- ---------------------------------------------------------------------------
--
-- alter table public.goals enable row level security;
-- alter table public.goals force row level security;
--
-- create policy goals_select_own
--   on public.goals
--   for select
--   using (
--     user_id = public.app_current_user_id()
--     and deleted_at is null
--   );
--
-- create policy goals_insert_own
--   on public.goals
--   for insert
--   with check (
--     user_id = public.app_current_user_id()
--   );
--
-- create policy goals_update_own
--   on public.goals
--   for update
--   using (
--     user_id = public.app_current_user_id()
--     and deleted_at is null
--   )
--   with check (
--     user_id = public.app_current_user_id()
--   );
--
-- create policy goals_delete_own
--   on public.goals
--   for delete
--   using (
--     user_id = public.app_current_user_id()
--   );

-- ---------------------------------------------------------------------------
-- Budget
-- Tables: public.monthly_budgets, public.budget_category_limits
-- ---------------------------------------------------------------------------
--
-- alter table public.monthly_budgets enable row level security;
-- alter table public.monthly_budgets force row level security;
--
-- create policy monthly_budgets_select_own
--   on public.monthly_budgets
--   for select
--   using (
--     user_id = public.app_current_user_id()
--     and deleted_at is null
--   );
--
-- create policy monthly_budgets_insert_own
--   on public.monthly_budgets
--   for insert
--   with check (
--     user_id = public.app_current_user_id()
--   );
--
-- create policy monthly_budgets_update_own
--   on public.monthly_budgets
--   for update
--   using (
--     user_id = public.app_current_user_id()
--     and deleted_at is null
--   )
--   with check (
--     user_id = public.app_current_user_id()
--   );
--
-- create policy monthly_budgets_delete_own
--   on public.monthly_budgets
--   for delete
--   using (
--     user_id = public.app_current_user_id()
--   );
--
-- alter table public.budget_category_limits enable row level security;
-- alter table public.budget_category_limits force row level security;
--
-- create policy budget_category_limits_select_own
--   on public.budget_category_limits
--   for select
--   using (
--     user_id = public.app_current_user_id()
--   );
--
-- create policy budget_category_limits_insert_own
--   on public.budget_category_limits
--   for insert
--   with check (
--     user_id = public.app_current_user_id()
--     and exists (
--       select 1
--       from public.monthly_budgets b
--       where b.id = budget_id
--         and b.user_id = public.app_current_user_id()
--         and b.deleted_at is null
--     )
--   );
--
-- create policy budget_category_limits_update_own
--   on public.budget_category_limits
--   for update
--   using (
--     user_id = public.app_current_user_id()
--   )
--   with check (
--     user_id = public.app_current_user_id()
--   );
--
-- create policy budget_category_limits_delete_own
--   on public.budget_category_limits
--   for delete
--   using (
--     user_id = public.app_current_user_id()
--   );
