import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma, type RecurringTransaction } from "@prisma/client";
import { AuditService } from "../audit/audit.service.js";
import { FINANCIAL_DATABASE, type FinancialDatabasePort, type FinancialTransactionPort } from "../financial/financial-database.port.js";
import { applyBalanceDelta, serializeDecimal } from "../financial/money.js";
import { CreateRecurringTransactionDto, ListRecurringTransactionsDto, UpdateRecurringTransactionDto } from "./dto/recurring-transaction.dto.js";

const money = /^(?!0(?:\.0{1,4})?$)\d{1,15}(?:\.\d{1,4})?$/; const currency = /^[A-Z]{3}$/;
type RecurringResponse = { id: string; accountId: string; categoryId: string | null; type: string; recurrenceKind: string; name: string; description: string | null; amount: string; currency: string; startDate: Date; endDate: Date | null; nextOccurrenceDate: Date; lastGeneratedAt: Date | null; isSubscription: boolean; providerName: string | null; status: string; createdAt: Date; updatedAt: Date };
type AuditPort = Pick<AuditService, "record">;
@Injectable()
export class RecurringTransactionsService {
  constructor(@Inject(FINANCIAL_DATABASE) private readonly prisma: FinancialDatabasePort, @Inject(AuditService) private readonly audit: AuditPort) {}
  async create(userId: string, dto: CreateRecurringTransactionDto): Promise<RecurringResponse> { this.assertCreate(dto); const start = this.date(dto.startDate, "INVALID_START_DATE"); const end = dto.endDate ? this.date(dto.endDate, "INVALID_END_DATE") : null; this.assertDateRange(start, end); this.assertNotPast(start); await this.references(this.prisma, userId, dto.accountId, dto.categoryId, dto.type, dto.currency ?? "BRL"); const record = await this.prisma.recurringTransaction.create({ data: { userId, accountId: dto.accountId, categoryId: dto.categoryId, type: dto.type, recurrenceKind: dto.recurrenceKind, name: dto.name.trim(), description: dto.description?.trim() || null, amount: new Prisma.Decimal(dto.amount), currency: dto.currency ?? "BRL", startDate: start, endDate: end, nextOccurrenceDate: start, isSubscription: dto.isSubscription ?? false, providerName: dto.providerName?.trim() || null } }); await this.record(userId, "recurring_transaction.create", record.id, "ENTITY_CREATED", "LOW"); return this.present(record); }
  async list(userId: string, query: ListRecurringTransactionsDto) { const page = this.page(query.page, 1, Number.MAX_SAFE_INTEGER), pageSize = this.page(query.pageSize, 20, 100), order = query.sortOrder ?? "desc", sortBy = query.sortBy ?? "nextOccurrenceDate"; const where: Prisma.RecurringTransactionWhereInput = { userId, deletedAt: null, status: query.status, type: query.type, recurrenceKind: query.recurrenceKind, accountId: query.accountId, categoryId: query.categoryId, currency: query.currency, nextOccurrenceDate: this.range(query.nextStartDate, query.nextEndDate), ...(query.search ? { OR: [{ name: { contains: query.search.trim(), mode: "insensitive" } }, { description: { contains: query.search.trim(), mode: "insensitive" } }] } : {}) }; const [records, total] = await this.prisma.$transaction([this.prisma.recurringTransaction.findMany({ where, orderBy: [{ [sortBy]: order }, { id: order }], skip: (page - 1) * pageSize, take: pageSize }), this.prisma.recurringTransaction.count({ where })]); return { data: records.map(item => this.present(item)), meta: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } }; }
  async findOne(userId: string, id: string): Promise<RecurringResponse> { return this.present(await this.require(this.prisma, userId, id)); }
  async update(userId: string, id: string, dto: UpdateRecurringTransactionDto): Promise<RecurringResponse> { if (dto.amount !== undefined) this.amount(dto.amount); const previous = await this.require(this.prisma, userId, id); const accountId = dto.accountId ?? previous.accountId, categoryId = dto.categoryId === undefined ? previous.categoryId : dto.categoryId, type = dto.type ?? previous.type, currencyValue = dto.currency ?? previous.currency, start = dto.startDate ? this.date(dto.startDate, "INVALID_START_DATE") : previous.startDate, end = dto.endDate === undefined ? previous.endDate : dto.endDate === null ? null : this.date(dto.endDate, "INVALID_END_DATE"); this.assertDateRange(start, end); await this.references(this.prisma, userId, accountId, categoryId, type, currencyValue); const recurrenceKind = dto.recurrenceKind ?? previous.recurrenceKind; const nextOccurrenceDate = dto.startDate || dto.recurrenceKind ? this.nextOnOrAfter(start, recurrenceKind, this.today()) : previous.nextOccurrenceDate; const record = await this.prisma.recurringTransaction.update({ where: { id }, data: { accountId, categoryId, type, recurrenceKind, name: dto.name?.trim(), description: dto.description === undefined ? undefined : dto.description?.trim() || null, amount: dto.amount ? new Prisma.Decimal(dto.amount) : undefined, currency: currencyValue, startDate: start, endDate: end, nextOccurrenceDate, isSubscription: dto.isSubscription, providerName: dto.providerName === undefined ? undefined : dto.providerName?.trim() || null } }); await this.record(userId, "recurring_transaction.update", id, "ENTITY_UPDATED", "LOW"); return this.present(record); }
  async pause(userId: string, id: string): Promise<RecurringResponse> { return this.changeStatus(userId, id, "ACTIVE", "PAUSED", "pause"); }
  async resume(userId: string, id: string): Promise<RecurringResponse> { const record = await this.require(this.prisma, userId, id); if (record.status !== "PAUSED") throw new ConflictException({ code: "RECURRING_TRANSACTION_NOT_PAUSED", message: "Recurring transaction is not paused" }); const next = this.nextOnOrAfter(record.startDate, record.recurrenceKind, this.today()); const updated = await this.prisma.recurringTransaction.update({ where: { id }, data: { status: "ACTIVE", nextOccurrenceDate: next } }); await this.record(userId, "recurring_transaction.resume", id, "ENTITY_UPDATED", "LOW"); return this.present(updated); }
  async cancel(userId: string, id: string): Promise<RecurringResponse> { const record = await this.require(this.prisma, userId, id); if (record.status === "ENDED") throw new ConflictException({ code: "RECURRING_TRANSACTION_ENDED", message: "Recurring transaction is already ended" }); const updated = await this.prisma.recurringTransaction.update({ where: { id }, data: { status: "ENDED" } }); await this.record(userId, "recurring_transaction.cancel", id, "ENTITY_UPDATED", "MEDIUM"); return this.present(updated); }
  async remove(userId: string, id: string): Promise<void> { await this.require(this.prisma, userId, id); await this.prisma.recurringTransaction.update({ where: { id }, data: { status: "DELETED", deletedAt: new Date() } }); await this.record(userId, "recurring_transaction.delete", id, "ENTITY_DELETED", "MEDIUM"); }
  async run(userId: string, id: string) { const created = await this.prisma.$transaction(async transaction => { const recurring = await this.require(transaction, userId, id); if (recurring.status !== "ACTIVE") throw new ConflictException({ code: "RECURRING_TRANSACTION_NOT_ACTIVE", message: "Recurring transaction is not active" }); const today = this.today(); if (recurring.nextOccurrenceDate > today) throw new ConflictException({ code: "RECURRING_TRANSACTION_NOT_DUE", message: "Recurring transaction is not due" }); if (recurring.endDate && recurring.nextOccurrenceDate > recurring.endDate) throw new ConflictException({ code: "RECURRING_TRANSACTION_ENDED", message: "Recurring transaction has ended" }); await this.references(transaction, userId, recurring.accountId, recurring.categoryId, recurring.type, recurring.currency); const next = this.nextOccurrence(recurring.startDate, recurring.nextOccurrenceDate, recurring.recurrenceKind); const status = recurring.endDate && next > recurring.endDate ? "ENDED" : "ACTIVE"; const claimed = await transaction.recurringTransaction.updateMany({ where: { id, userId, deletedAt: null, status: "ACTIVE", nextOccurrenceDate: recurring.nextOccurrenceDate }, data: { nextOccurrenceDate: next, lastGeneratedAt: new Date(), status } }); if (claimed.count !== 1) throw new ConflictException({ code: "RECURRING_OCCURRENCE_ALREADY_PROCESSED", message: "Recurring occurrence already processed" }); const transactionRecord = await transaction.transaction.create({ data: { userId, accountId: recurring.accountId, categoryId: recurring.categoryId, type: recurring.type, status: "CONFIRMED", description: recurring.description ?? recurring.name, amount: recurring.amount, transactionDate: recurring.nextOccurrenceDate, source: "RECURRING", recurringTransactionId: recurring.id } }); await applyBalanceDelta(transaction, recurring.accountId, recurring.type, recurring.amount); return transactionRecord; }); await this.record(userId, "recurring_transaction.run", id, "ENTITY_CREATED", "MEDIUM"); return { id: created.id, accountId: created.accountId, categoryId: created.categoryId, type: created.type, status: created.status, description: created.description, amount: serializeDecimal(created.amount), transactionDate: created.transactionDate, recurringTransactionId: created.recurringTransactionId }; }
  private async changeStatus(userId: string, id: string, expected: string, status: "PAUSED", action: string): Promise<RecurringResponse> { const record = await this.require(this.prisma, userId, id); if (record.status !== expected) throw new ConflictException({ code: "INVALID_RECURRING_TRANSACTION_STATUS", message: "Invalid recurring transaction status" }); const updated = await this.prisma.recurringTransaction.update({ where: { id }, data: { status } }); await this.record(userId, `recurring_transaction.${action}`, id, "ENTITY_UPDATED", "LOW"); return this.present(updated); }
  private async require(database: FinancialTransactionPort, userId: string, id: string): Promise<RecurringTransaction> { const record = await database.recurringTransaction.findFirst({ where: { id, userId, deletedAt: null } }); if (!record) throw new NotFoundException({ code: "RECURRING_TRANSACTION_NOT_FOUND", message: "Recurring transaction not found" }); return record; }
  private async references(database: FinancialTransactionPort, userId: string, accountId: string, categoryId: string | null | undefined, type: string, expectedCurrency: string): Promise<void> { const account = await database.account.findFirst({ where: { id: accountId, userId, status: "ACTIVE", deletedAt: null } }); if (!account) throw new NotFoundException({ code: "ACCOUNT_NOT_FOUND", message: "Account not found" }); if (account.currency !== expectedCurrency) throw new ConflictException({ code: "ACCOUNT_CURRENCY_MISMATCH", message: "Account currency is incompatible" }); if (!categoryId) return; const category = await database.category.findFirst({ where: { id: categoryId, deletedAt: null, OR: [{ userId }, { userId: null, isDefault: true }] } }); if (!category) throw new NotFoundException({ code: "CATEGORY_NOT_FOUND", message: "Category not found" }); if (category.type !== "BOTH" && category.type !== type) throw new ConflictException({ code: "CATEGORY_INCOMPATIBLE", message: "Category is incompatible" }); }
  private present(record: RecurringTransaction): RecurringResponse { return { id: record.id, accountId: record.accountId, categoryId: record.categoryId, type: record.type, recurrenceKind: record.recurrenceKind, name: record.name, description: record.description, amount: serializeDecimal(record.amount), currency: record.currency, startDate: record.startDate, endDate: record.endDate, nextOccurrenceDate: record.nextOccurrenceDate, lastGeneratedAt: record.lastGeneratedAt, isSubscription: record.isSubscription, providerName: record.providerName, status: record.status, createdAt: record.createdAt, updatedAt: record.updatedAt }; }
  private amount(value: string): void { if (!money.test(value)) throw new BadRequestException({ code: "INVALID_AMOUNT", message: "Invalid amount" }); }
  private assertCreate(dto: CreateRecurringTransactionDto): void { this.amount(dto.amount); if (!dto.name.trim()) throw new BadRequestException({ code: "INVALID_RECURRING_NAME", message: "Invalid name" }); if (dto.currency !== undefined && !currency.test(dto.currency)) throw new BadRequestException({ code: "INVALID_CURRENCY", message: "Invalid currency" }); }
  private date(value: string, code: string): Date { const result = new Date(value); if (Number.isNaN(result.getTime())) throw new BadRequestException({ code, message: "Invalid date" }); return result; }
  private today(): Date { const now = new Date(); return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())); }
  private assertNotPast(date: Date): void { if (date < this.today()) throw new BadRequestException({ code: "START_DATE_IN_PAST", message: "Start date cannot be in the past" }); }
  private assertDateRange(start: Date, end: Date | null): void { if (end && end < start) throw new BadRequestException({ code: "INVALID_DATE_RANGE", message: "End date cannot precede start date" }); }
  private nextOccurrence(anchor: Date, current: Date, kind: string): Date { if (kind === "WEEKLY") return new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth(), current.getUTCDate() + 7)); if (kind === "YEARLY") return this.clampedDate(current.getUTCFullYear() + 1, anchor.getUTCMonth(), anchor.getUTCDate()); return this.clampedDate(current.getUTCFullYear(), current.getUTCMonth() + 1, anchor.getUTCDate()); }
  private nextOnOrAfter(anchor: Date, kind: string, minimum: Date): Date { let candidate = anchor; while (candidate < minimum) candidate = this.nextOccurrence(anchor, candidate, kind); return candidate; }
  private clampedDate(year: number, month: number, day: number): Date { const last = new Date(Date.UTC(year, month + 1, 0)).getUTCDate(); return new Date(Date.UTC(year, month, Math.min(day, last))); }
  private range(start?: string, end?: string): Prisma.DateTimeFilter | undefined { if (!start && !end) return undefined; const result: Prisma.DateTimeFilter = {}; if (start) result.gte = this.date(start, "INVALID_DATE_RANGE"); if (end) result.lte = this.date(end, "INVALID_DATE_RANGE"); if (result.gte && result.lte && result.gte > result.lte) throw new BadRequestException({ code: "INVALID_DATE_RANGE", message: "Invalid date range" }); return result; }
  private page(value: number | undefined, fallback: number, maximum: number): number { const candidate = value ?? fallback, parsed = typeof candidate === "number" ? candidate : Number.parseInt(String(candidate), 10); if (!Number.isInteger(parsed) || parsed < 1 || parsed > maximum) throw new BadRequestException({ code: "INVALID_PAGINATION", message: "Invalid pagination" }); return parsed; }
  private async record(userId: string, action: string, entityId: string, eventType: "ENTITY_CREATED" | "ENTITY_UPDATED" | "ENTITY_DELETED", riskLevel: "LOW" | "MEDIUM"): Promise<void> { await this.audit.record({ action, actorUserId: userId, entityId, entityType: "recurring_transaction", eventType, riskLevel, userId }); }
}
