import { BadRequestException, ConflictException, NotFoundException } from "@nestjs/common";
import { AccountStatus, CategoryType, Prisma, RecurrenceKind, RecurringTransactionStatus } from "@prisma/client";
import { RecurrenceKindDto, RecurringTypeDto } from "./dto/recurring-transaction.dto.js";
import { RecurringTransactionsService } from "./recurring-transactions.service.js";
import { createAccount, createAuthenticatedUser, createCategory, createRecurringTransaction, createTransaction, testDate, testDecimal, testUuid } from "../../test-utils/financial-fixtures.js";
import { createFinancialPrismaMock } from "../../test-utils/financial-prisma.mock.js";

describe("RecurringTransactionsService", () => {
  const user = createAuthenticatedUser(); const audit = { record: jest.fn<Promise<void>, [never]>() }; let prisma = createFinancialPrismaMock(); let service: RecurringTransactionsService;
  const today = (): Date => { const now = new Date(); return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())); };
  const recurring = (overrides = {}) => createRecurringTransaction({ id: testUuid(20), userId: user.id, startDate: today(), nextOccurrenceDate: today(), ...overrides });
  beforeEach(() => { prisma = createFinancialPrismaMock(); audit.record.mockResolvedValue(undefined); service = new RecurringTransactionsService(prisma, audit); });
  function references(): void { prisma.account.findFirst.mockResolvedValue(createAccount({ id: testUuid(2), userId: user.id, currency: "BRL", status: AccountStatus.ACTIVE })); prisma.category.findFirst.mockResolvedValue(createCategory({ id: testUuid(3), userId: user.id, type: CategoryType.EXPENSE })); }
  it("creates an owned recurring transaction with decimal data and initial next date", async () => { references(); const startDate = new Date(Date.now() + 86_400_000).toISOString().slice(0, 10); prisma.recurringTransaction.create.mockResolvedValue(recurring({ startDate: testDate(`${startDate}T00:00:00.000Z`), nextOccurrenceDate: testDate(`${startDate}T00:00:00.000Z`) })); const result = await service.create(user.id, { accountId: testUuid(2), categoryId: testUuid(3), type: RecurringTypeDto.EXPENSE, recurrenceKind: RecurrenceKindDto.MONTHLY, name: "Streaming", amount: "19.9900", startDate }); expect(prisma.recurringTransaction.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ userId: user.id, amount: expect.any(Prisma.Decimal) }) })); expect(result.amount).toBe("20"); });
  it.each(["0", "-1", "1.00001", "1e3", "NaN", "Infinity"])("rejects invalid amount %s", async amount => { await expect(service.create(user.id, { accountId: testUuid(2), type: RecurringTypeDto.EXPENSE, recurrenceKind: RecurrenceKindDto.WEEKLY, name: "X", amount, startDate: "2099-01-01" })).rejects.toBeInstanceOf(BadRequestException); });
  it("rejects an end date preceding the start date", async () => { await expect(service.create(user.id, { accountId: testUuid(2), type: RecurringTypeDto.EXPENSE, recurrenceKind: RecurrenceKindDto.MONTHLY, name: "X", amount: "1", startDate: "2099-02-01", endDate: "2099-01-01" })).rejects.toBeInstanceOf(BadRequestException); });
  it("lists user-owned non-deleted records with a stable order", async () => { prisma.recurringTransaction.findMany.mockResolvedValue([recurring()]); prisma.recurringTransaction.count.mockResolvedValue(1); const result = await service.list(user.id, { page: 1, pageSize: 20 }); expect(prisma.transactionCalls).toBe(1); expect(prisma.recurringTransaction.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ userId: user.id, deletedAt: null }), orderBy: [{ nextOccurrenceDate: "desc" }, { id: "desc" }] })); expect(result.meta.total).toBe(1); });
  it("hides another user recurrence", async () => { prisma.recurringTransaction.findFirst.mockResolvedValue(null); await expect(service.findOne(user.id, testUuid(20))).rejects.toBeInstanceOf(NotFoundException); });
  it("uses calendar-aware monthly and leap-year date progression", async () => { jest.useFakeTimers().setSystemTime(testDate("2028-01-31T12:00:00.000Z")); try { const jan31 = testDate("2028-01-31T00:00:00.000Z"); const item = recurring({ startDate: jan31, nextOccurrenceDate: jan31, recurrenceKind: RecurrenceKind.MONTHLY }); references(); prisma.recurringTransaction.findFirst.mockResolvedValue(item); prisma.recurringTransaction.updateMany.mockResolvedValue({ count: 1 }); prisma.transaction.create.mockResolvedValue(createTransaction({ recurringTransactionId: item.id, transactionDate: jan31 })); prisma.account.update.mockResolvedValue(createAccount()); await service.run(user.id, item.id); expect(prisma.recurringTransaction.updateMany).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ nextOccurrenceDate: testDate("2028-02-29T00:00:00.000Z") }) })); } finally { jest.useRealTimers(); } });
  it("creates one recurring transaction and applies the account delta", async () => { const item = recurring(); references(); prisma.recurringTransaction.findFirst.mockResolvedValue(item); prisma.recurringTransaction.updateMany.mockResolvedValue({ count: 1 }); prisma.transaction.create.mockResolvedValue(createTransaction({ recurringTransactionId: item.id, amount: testDecimal("20") })); prisma.account.update.mockResolvedValue(createAccount()); const result = await service.run(user.id, item.id); expect(prisma.transactionCalls).toBe(1); expect(prisma.transaction.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ recurringTransactionId: item.id, source: "RECURRING", status: "CONFIRMED" }) })); expect(prisma.account.update).toHaveBeenCalled(); expect(result.amount).toBe("20"); });
  it("blocks a duplicate or concurrent occurrence claim", async () => { const item = recurring(); references(); prisma.recurringTransaction.findFirst.mockResolvedValue(item); prisma.recurringTransaction.updateMany.mockResolvedValue({ count: 0 }); await expect(service.run(user.id, item.id)).rejects.toBeInstanceOf(ConflictException); expect(prisma.transaction.create).not.toHaveBeenCalled(); });
  it("blocks run while paused and preserves prior generated transactions", async () => { prisma.recurringTransaction.findFirst.mockResolvedValue(recurring({ status: RecurringTransactionStatus.PAUSED })); await expect(service.run(user.id, testUuid(20))).rejects.toBeInstanceOf(ConflictException); });
  it("pauses and resumes from the next future occurrence without catch-up", async () => { const item = recurring({ status: RecurringTransactionStatus.ACTIVE, startDate: testDate("2020-01-31T00:00:00.000Z"), nextOccurrenceDate: testDate("2020-01-31T00:00:00.000Z") }); prisma.recurringTransaction.findFirst.mockResolvedValueOnce(item).mockResolvedValueOnce({ ...item, status: RecurringTransactionStatus.PAUSED }); prisma.recurringTransaction.update.mockResolvedValue({ ...item, status: RecurringTransactionStatus.PAUSED }); await service.pause(user.id, item.id); prisma.recurringTransaction.update.mockResolvedValue({ ...item, status: RecurringTransactionStatus.ACTIVE, nextOccurrenceDate: today() }); await service.resume(user.id, item.id); expect(prisma.recurringTransaction.update).toHaveBeenLastCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: "ACTIVE" }) })); });
  it("cancels and soft deletes without deleting historical transactions", async () => { const item = recurring(); prisma.recurringTransaction.findFirst.mockResolvedValue(item); prisma.recurringTransaction.update.mockResolvedValue({ ...item, status: RecurringTransactionStatus.ENDED }); await service.cancel(user.id, item.id); prisma.recurringTransaction.findFirst.mockResolvedValue(item); await service.remove(user.id, item.id); expect(prisma.transaction.update).not.toHaveBeenCalled(); expect(prisma.recurringTransaction.update).toHaveBeenLastCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: "DELETED", deletedAt: expect.any(Date) }) })); });
});
