/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-call */
import { AuditService } from "../audit/audit.service.js";
import { PrismaService } from "../prisma/prisma.service.js";
import { AccountsService } from "./accounts.service.js";

const userId = "11111111-1111-4111-8111-111111111111";
const otherUserId = "22222222-2222-4222-8222-222222222222";
const account = (id = "33333333-3333-4333-8333-333333333333", owner = userId) => ({ archivedAt: null, color: null, createdAt: new Date(), currency: "BRL", currentBalance: { toString: () => "10.5000" }, deletedAt: null, id, icon: null, includeInDashboard: true, initialBalance: { toString: () => "10.5000" }, name: "Wallet", status: "ACTIVE", type: "WALLET", updatedAt: new Date(), userId: owner });
function harness() { const rows = [account()]; const prisma: any = { account: { create: jest.fn(({ data }) => Promise.resolve(account("44444444-4444-4444-8444-444444444444", data.userId))), findFirst: jest.fn(({ where }) => Promise.resolve(rows.find((row) => row.id === where.id && row.userId === where.userId && !row.deletedAt) ?? null)), findMany: jest.fn(({ where }) => Promise.resolve(rows.filter((row) => row.userId === where.userId && !row.deletedAt))), update: jest.fn(({ data, where }) => { const row = rows.find((item) => item.id === where.id)!; Object.assign(row, data); return Promise.resolve(row); }) }, transaction: { count: jest.fn().mockResolvedValue(0) }, transfer: { count: jest.fn().mockResolvedValue(0) }, recurringTransaction: { count: jest.fn().mockResolvedValue(0) }, importBatch: { count: jest.fn().mockResolvedValue(0) }, importItem: { count: jest.fn().mockResolvedValue(0) }, accountBalanceSnapshot: { count: jest.fn().mockResolvedValue(0) }, auditLog: { create: jest.fn().mockResolvedValue({}) } }; return { prisma, rows, service: new AccountsService(prisma as PrismaService, new AuditService(prisma as PrismaService)) }; }
describe("AccountsService", () => {
  it("creates a user-owned account and serializes decimal balances as strings", async () => { const { service, prisma } = harness(); const result = await service.create(userId, { initialBalance: "10.5000", name: "Cash", type: "WALLET" as any }); expect(prisma.account.create.mock.calls[0][0].data).toMatchObject({ currentBalance: "10.5000", initialBalance: "10.5000", userId }); expect(result.currentBalance).toBe("10.5000"); });
  it("lists only active non-deleted accounts for the authenticated user", async () => { const { service } = harness(); await expect(service.list(userId)).resolves.toHaveLength(1); });
  it("does not disclose an account owned by another user", async () => { const { service } = harness(); await expect(service.findOne(otherUserId, "33333333-3333-4333-8333-333333333333")).rejects.toMatchObject({ status: 404 }); });
  it("updates only editable fields", async () => { const { service, prisma } = harness(); await service.update(userId, "33333333-3333-4333-8333-333333333333", { name: "Updated" }); expect(prisma.account.update.mock.calls[0][0].data).not.toHaveProperty("userId"); });
  it("soft-deletes an unused account", async () => { const { service, rows } = harness(); const row = rows[0]!; await service.remove(userId, row.id); expect(row.status).toBe("DELETED"); expect(row.deletedAt).toBeInstanceOf(Date); });
  it("rejects deletion when related records exist", async () => { const { service, prisma } = harness(); prisma.transaction.count.mockResolvedValueOnce(1); await expect(service.remove(userId, "33333333-3333-4333-8333-333333333333")).rejects.toMatchObject({ status: 409 }); });
});
