"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { useForm, type Resolver } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useAuth } from "@/stores/auth";

type FormValues = { email: string; password: string; name?: string; confirm?: string };
const loginSchema = z.object({ email: z.string().email("Informe um e-mail válido."), password: z.string().min(8, "A senha deve ter ao menos 8 caracteres.") });
const registerSchema = loginSchema.extend({ name: z.string().min(2, "Informe seu nome."), confirm: z.string() }).refine((value) => value.password === value.confirm, { path: ["confirm"], message: "As senhas não coincidem." });

function Mark() { return <span className="auth-mark" aria-hidden="true"><span /></span>; }

export function AuthForm({ mode }: { mode: "login" | "register" }) {
  const router = useRouter();
  const params = useSearchParams();
  const auth = useAuth();
  const [error, setError] = useState("");
  const schema = mode === "login" ? loginSchema : registerSchema;
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema) as Resolver<FormValues> });
  const submit = handleSubmit(async (values) => { setError(""); try { if (mode === "register") { await auth.register({ name: values.name ?? "", email: values.email, password: values.password }); await auth.login(values.email, values.password); } else await auth.login(values.email, values.password); router.replace(params.get("next") ?? "/dashboard"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível entrar."); } });

  return <main className="auth"><section><div className="auth-brand"><Mark /><strong>Atlas Finance</strong></div><div className="auth-content"><h1>{mode === "login" ? "Bem-vindo de volta" : "Comece sua organização financeira"}</h1><p>{mode === "login" ? "Entre para acompanhar seus dados com clareza e precisão." : "Crie sua conta para organizar decisões com base nos seus próprios registros."}</p><form onSubmit={submit}>{mode === "register" && <div className="field"><label htmlFor="name">Nome</label><input id="name" autoComplete="name" {...register("name")} aria-invalid={Boolean(errors.name)} /><small>{errors.name?.message}</small></div>}<div className="field"><label htmlFor="email">E-mail</label><input id="email" type="email" autoComplete="email" {...register("email")} aria-invalid={Boolean(errors.email)} /><small>{errors.email?.message}</small></div><div className="field"><label htmlFor="password">Senha</label><input id="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} {...register("password")} aria-invalid={Boolean(errors.password)} /><small>{errors.password?.message}</small></div>{mode === "register" && <div className="field"><label htmlFor="confirm">Confirmar senha</label><input id="confirm" type="password" autoComplete="new-password" {...register("confirm")} aria-invalid={Boolean(errors.confirm)} /><small>{errors.confirm?.message}</small></div>}{error && <div role="alert" className="auth-error">{error}</div>}<button className="btn primary" disabled={isSubmitting}>{isSubmitting ? "Aguarde…" : mode === "login" ? "Entrar" : "Criar conta"}</button></form><p className="switch">{mode === "login" ? "Ainda não tem uma conta? " : "Já possui uma conta? "}<Link href={mode === "login" ? "/register" : "/login"}>{mode === "login" ? "Cadastre-se" : "Entrar"}</Link></p></div><footer>Seus dados financeiros são tratados com segurança. Valores não são recalculados no navegador.</footer></section><aside><div><span>ATLAS MINERAL</span><blockquote>Clareza para entender o presente. Precisão para decidir o próximo passo.</blockquote><p>Patrimônio, planejamento e análises organizados por moeda.</p></div></aside><style jsx>{`
    .auth{min-height:100vh;display:grid;grid-template-columns:minmax(420px,610px) 1fr;background:var(--surface)}.auth>section{padding:36px clamp(28px,6vw,82px);display:flex;flex-direction:column;justify-content:space-between}.auth-brand{display:flex;align-items:center;gap:11px;font-size:17px}.auth-mark{width:24px;height:28px;display:grid;place-items:center;transform:rotate(45deg);border-radius:5px;background:linear-gradient(135deg,#25b88b,#0b715c);overflow:hidden}.auth-mark span{width:1px;height:34px;background:#a4e4cf;opacity:.7;transform:rotate(-18deg)}.auth-content{margin-block:auto;padding:55px 0}.auth h1{font-size:clamp(34px,4vw,48px);max-width:480px;margin:0 0 12px;line-height:1.08;letter-spacing:-.055em}.auth p{color:var(--muted);line-height:1.65;max-width:470px}.auth form{display:flex;flex-direction:column;gap:14px;margin-top:28px;max-width:440px}.auth .field small{min-height:13px}.auth-error{padding:12px 14px;background:#fff2f0;color:var(--critical);border-left:3px solid var(--critical);font-size:13px}.auth .switch{font-size:13px}.auth .switch a{color:var(--atlas);font-weight:750}.auth footer{font-size:11px;color:var(--muted);max-width:440px}.auth>aside{background:var(--nav);color:#fff;padding:clamp(44px,7vw,96px);display:flex;align-items:center;position:relative;overflow:hidden}.auth>aside:after{content:"";position:absolute;width:520px;height:520px;border:1px solid #2c5c5d;border-radius:50%;right:-280px;top:-180px;box-shadow:0 0 0 70px rgb(40 103 92/.08),0 0 0 140px rgb(40 103 92/.05)}.auth>aside>div{position:relative;z-index:1}.auth>aside span{font-size:10px;letter-spacing:.15em;color:#7fd2b7}.auth blockquote{font-size:clamp(35px,4vw,58px);line-height:1.08;letter-spacing:-.055em;max-width:720px;margin:18px 0}.auth>aside p{color:#b6cfcb;font-size:15px}@media(max-width:800px){.auth{display:block}.auth>section{min-height:100vh;padding:25px 21px}.auth>aside{display:none}.auth-content{padding:44px 0 30px}.auth h1{font-size:34px}.auth footer{margin-top:30px}}
  `}</style></main>;
}
