"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Filter, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { ApiError, api } from "@/lib/api/client";
import { formatDate, formatMoney, normalizeMoneyInput } from "@/lib/format";

type Field = { name: string; label: string; type?: "text" | "money" | "date" | "select" | "checkbox"; options?: string[]; required?: boolean };
type Config = { title: string; description: string; endpoint: string; create?: Field[]; columns: [string, string, "money" | "date" | "text"][]; empty: string; query?: Record<string, string | number>; actions?: { label: string; suffix: string; method?: string }[] };

export const configs: Record<string, Config> = {
  accounts: { title: "Contas", description: "Saldos por instituição e moeda, sem representações bancárias artificiais.", endpoint: "/accounts", empty: "Você ainda não possui contas.", create: [{ name: "name", label: "Nome", required: true }, { name: "type", label: "Tipo", type: "select", options: ["CHECKING", "DIGITAL", "WALLET", "INVESTMENT", "CARD"], required: true }, { name: "currency", label: "Moeda", type: "select", options: ["BRL", "USD", "EUR"], required: true }, { name: "initialBalance", label: "Saldo inicial", type: "money", required: true }], columns: [["name", "Conta", "text"], ["type", "Tipo", "text"], ["currency", "Moeda", "text"], ["currentBalance", "Saldo atual", "money"], ["status", "Status", "text"]] },
  transactions: { title: "Transações", description: "Receitas, despesas e ajustes registrados.", endpoint: "/transactions", empty: "Não há movimentações neste período.", query: { page: 1, pageSize: 20 }, create: [{ name: "accountId", label: "ID da conta", required: true }, { name: "categoryId", label: "ID da categoria" }, { name: "type", label: "Tipo", type: "select", options: ["INCOME", "EXPENSE", "ADJUSTMENT"], required: true }, { name: "amount", label: "Valor", type: "money", required: true }, { name: "description", label: "Descrição", required: true }, { name: "transactionDate", label: "Data", type: "date", required: true }, { name: "status", label: "Status", type: "select", options: ["CONFIRMED", "PENDING", "IGNORED"] }], columns: [["transactionDate", "Data", "date"], ["description", "Descrição", "text"], ["type", "Tipo", "text"], ["currency", "Moeda", "text"], ["amount", "Valor", "money"], ["status", "Status", "text"]] },
  transfers: { title: "Transferências", description: "Movimentações atômicas entre suas contas.", endpoint: "/transfers", empty: "Nenhuma transferência registrada.", query: { page: 1, pageSize: 20 }, create: [{ name: "fromAccountId", label: "Conta de origem", required: true }, { name: "toAccountId", label: "Conta de destino", required: true }, { name: "amount", label: "Valor", type: "money", required: true }, { name: "transferDate", label: "Data", type: "date", required: true }, { name: "description", label: "Descrição" }], columns: [["transferDate", "Data", "date"], ["description", "Descrição", "text"], ["amount", "Valor", "money"], ["status", "Status", "text"]] },
  budgets: { title: "Orçamentos", description: "Limites mensais e consumo calculado pela API.", endpoint: "/budgets", empty: "Nenhum orçamento configurado.", query: { page: 1, pageSize: 20 }, create: [{ name: "month", label: "Mês (AAAA-MM)", required: true }, { name: "currency", label: "Moeda", type: "select", options: ["BRL", "USD", "EUR"], required: true }, { name: "name", label: "Nome" }], columns: [["month", "Mês", "text"], ["currency", "Moeda", "text"], ["totalLimit", "Limite", "money"], ["totalSpent", "Gasto", "money"], ["status", "Status", "text"]] },
  goals: { title: "Metas", description: "Objetivos, contribuições e progresso real.", endpoint: "/goals", empty: "Crie uma meta para começar a planejar.", query: { page: 1, pageSize: 20 }, create: [{ name: "name", label: "Nome", required: true }, { name: "type", label: "Tipo", type: "select", options: ["GENERIC", "EMERGENCY_FUND", "TRAVEL", "VEHICLE", "PROPERTY", "RETIREMENT", "PURCHASE"], required: true }, { name: "targetAmount", label: "Valor alvo", type: "money", required: true }, { name: "currency", label: "Moeda", type: "select", options: ["BRL", "USD", "EUR"], required: true }, { name: "targetDate", label: "Data alvo", type: "date" }, { name: "priority", label: "Prioridade", type: "select", options: ["LOW", "MEDIUM", "HIGH"] }], columns: [["name", "Meta", "text"], ["type", "Tipo", "text"], ["targetAmount", "Objetivo", "money"], ["currentAmount", "Acumulado", "money"], ["progressPercentage", "Progresso", "text"], ["status", "Status", "text"]] },
  recurring: { title: "Recorrências", description: "Compromissos previstos, frequência e próxima ocorrência.", endpoint: "/recurring-transactions", empty: "Nenhuma recorrência cadastrada.", query: { page: 1, pageSize: 20 }, create: [{ name: "accountId", label: "ID da conta", required: true }, { name: "name", label: "Nome", required: true }, { name: "type", label: "Tipo", type: "select", options: ["INCOME", "EXPENSE"], required: true }, { name: "recurrenceKind", label: "Frequência", type: "select", options: ["WEEKLY", "MONTHLY", "YEARLY"], required: true }, { name: "amount", label: "Valor", type: "money", required: true }, { name: "startDate", label: "Início", type: "date", required: true }], columns: [["name", "Recorrência", "text"], ["type", "Tipo", "text"], ["amount", "Valor", "money"], ["nextOccurrenceDate", "Próxima", "date"], ["status", "Status", "text"]] },
  insights: { title: "Insights", description: "Um briefing financeiro baseado nos dados registrados.", endpoint: "/insights", empty: "Nenhuma condição relevante foi detectada.", query: { page: 1, pageSize: 20 }, columns: [["title", "Análise", "text"], ["severity", "Severidade", "text"], ["currency", "Moeda", "text"], ["status", "Status", "text"], ["createdAt", "Criado em", "date"]], actions: [{ label: "Marcar como lido", suffix: "read", method: "PATCH" }, { label: "Dispensar", suffix: "dismiss", method: "PATCH" }] },
};

function rows(data: unknown): Record<string, unknown>[] { if (Array.isArray(data)) return data as Record<string, unknown>[]; if (data && typeof data === "object" && "data" in data && Array.isArray((data as { data: unknown }).data)) return (data as { data: Record<string, unknown>[] }).data; return []; }
const translate = (value: unknown) => ({ CHECKING: "Conta corrente", DIGITAL: "Conta digital", WALLET: "Carteira", INVESTMENT: "Investimento", CARD: "Cartão", INCOME: "Receita", EXPENSE: "Despesa", ADJUSTMENT: "Ajuste", CONFIRMED: "Confirmado", PENDING: "Pendente", IGNORED: "Ignorado", WEEKLY: "Semanal", MONTHLY: "Mensal", YEARLY: "Anual", EMERGENCY_FUND: "Reserva de emergência", GENERIC: "Geral", TRAVEL: "Viagem", VEHICLE: "Veículo", PROPERTY: "Imóvel", RETIREMENT: "Aposentadoria", PURCHASE: "Compra", LOW: "Baixa", MEDIUM: "Média", HIGH: "Alta", INFO: "Informativo", OPPORTUNITY: "Oportunidade", WARNING: "Atenção", CRITICAL: "Crítico" }[String(value)] ?? String(value ?? "—"));

export function ResourcePage({ kind }: { kind: string }) {
  const config = configs[kind];
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: [kind, config.query], queryFn: () => api(config.endpoint, { query: config.query }) });
  const create = useMutation({ mutationFn: (body: Record<string, unknown>) => api(config.endpoint, { method: "POST", body }), onSuccess: () => { toast.success("Registro criado com sucesso."); setOpen(false); void queryClient.invalidateQueries({ queryKey: [kind] }); }, onError: (error: Error) => toast.error(error.message || "Operação não concluída.") });
  const remove = useMutation({ mutationFn: (id: string) => api(`${config.endpoint}/${id}`, { method: "DELETE" }), onSuccess: () => { toast.success("Registro removido."); void queryClient.invalidateQueries({ queryKey: [kind] }); } });
  const data = rows(query.data);
  const filtered = useMemo(() => data.filter((row) => { const matchesSearch = !search || Object.values(row).some((value) => String(value).toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))); const matchesStatus = !status || String(row.status ?? row.severity ?? "") === status; return matchesSearch && matchesStatus; }), [data, search, status]);

  if (kind === "insights") return <InsightsBriefing data={data} loading={query.isLoading} error={query.isError} retry={() => void query.refetch()} />;

  return <div className={`page resource-page ${kind}`}>
    <div className="page-head"><div><h1>{config.title}</h1><p>{config.description}</p></div>{config.create && <button className="btn primary" onClick={() => setOpen(true)}><Plus /> Novo registro</button>}</div>
    <section className="filters" aria-label="Filtros"><label><span className="sr-only">Buscar nesta página</span><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar nos resultados" /></label><label><Filter /><span className="sr-only">Filtrar por status</span><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filtrar por status"><option value="">Todos os status</option><option value="CONFIRMED">Confirmado</option><option value="PENDING">Pendente</option><option value="ACTIVE">Ativo</option><option value="PAUSED">Pausado</option></select></label>{(search || status) && <button className="btn" onClick={() => { setSearch(""); setStatus(""); }}>Limpar filtros</button>}</section>
    {query.isLoading ? <><div className="skeleton" /><div className="skeleton" /></> : query.isError ? <ErrorPanel error={query.error} retry={() => void query.refetch()} /> : filtered.length === 0 ? <div className="empty-state"><div><h2>{data.length ? "Nenhum resultado para os filtros" : config.empty}</h2><p>{data.length ? "Ajuste ou limpe os filtros para ver os registros." : "Os dados aparecerão aqui assim que forem registrados."}</p>{config.create && !data.length ? <button className="btn primary" onClick={() => setOpen(true)}>Começar agora</button> : null}</div></div> : <><DesktopTable config={config} rows={filtered} remove={(id) => { if (confirm("Remover este registro?")) remove.mutate(id); }} /><MobileList kind={kind} config={config} rows={filtered} /></>}
    {open && config.create ? <CreateDialog title={config.title} fields={config.create} pending={create.isPending} close={() => setOpen(false)} submit={(value) => create.mutate(value)} transfer={kind === "transfers"} /> : null}
    <style jsx>{`.filters{display:flex;gap:10px;align-items:center;padding:12px 0;border-block:1px solid var(--border)}.filters label{display:flex;align-items:center;min-height:42px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface);padding:0 10px;gap:7px}.filters label:first-child{min-width:min(340px,100%)}.filters :global(svg){width:16px;color:var(--muted)}.filters input,.filters select{border:0;outline:0;background:transparent;min-width:0;width:100%}.filters select{min-width:155px}@media(max-width:700px){.filters{display:grid;grid-template-columns:1fr 1fr}.filters label:first-child{grid-column:1/-1}.filters .btn{grid-column:1/-1}.resource-page :global(.table-wrap){display:none}}@media(min-width:701px){.resource-page :global(.mobile-financial-list){display:none}}`}</style>
  </div>;
}

function DesktopTable({ config, rows: data, remove }: { config: Config; rows: Record<string, unknown>[]; remove: (id: string) => void }) { return <div className="table-wrap"><table className="table"><caption>{data.length} {data.length === 1 ? "registro" : "registros"} nesta página</caption><thead><tr>{config.columns.map(([, label]) => <th key={label}>{label}</th>)}<th><span className="sr-only">Ações</span></th></tr></thead><tbody>{data.map((row, index) => <tr key={String(row.id ?? index)}>{config.columns.map(([key,, type]) => <td key={key} className={type === "money" ? "numeric amount" : ""}>{type === "money" ? formatMoney(String(row[key] ?? ""), String(row.currency ?? "BRL")) : type === "date" ? formatDate(String(row[key] ?? "")) : key === "progressPercentage" ? <div className="table-progress"><span>{String(row[key] ?? "0")}%</span><div className="progress"><span style={{ width: `${Math.min(100, Number(row[key] ?? 0))}%` }} /></div></div> : key === "status" ? <span className={`status ${/ACTIVE|CONFIRMED|COMPLETED/.test(String(row[key])) ? "positive" : /OVER|LATE/.test(String(row[key])) ? "critical" : ""}`}>{translate(row[key])}</span> : translate(row[key])}</td>)}<td className="numeric"><button className="icon-button" aria-label={`Excluir ${String(row.name ?? row.description ?? "registro")}`} onClick={() => remove(String(row.id))}><Trash2 /></button></td></tr>)}</tbody></table><style jsx>{`.table-progress{display:flex;align-items:center;gap:10px}.table-progress>.progress{width:80px}`}</style></div>; }

function MobileList({ kind, config, rows: data }: { kind: string; config: Config; rows: Record<string, unknown>[] }) { return <div className="mobile-financial-list">{data.map((row, index) => { const title = row.description ?? row.name ?? row.fileName ?? `${config.title} ${index + 1}`; const amount = row.amount ?? row.currentBalance ?? row.currentAmount ?? row.totalSpent; const date = row.transactionDate ?? row.nextOccurrenceDate ?? row.targetDate ?? row.month; return <article key={String(row.id ?? index)}><div className="mobile-main"><strong>{String(title)}</strong><span>{translate(row.categoryName ?? row.type ?? row.status)}</span>{kind === "goals" && <div className="progress"><span style={{ width: `${Math.min(100, Number(row.progressPercentage ?? 0))}%` }} /></div>}</div><div className="mobile-meta">{amount !== undefined && <b className="amount">{formatMoney(String(amount), String(row.currency ?? "BRL"))}</b>}<span>{date ? (String(date).includes("-") && String(date).length > 7 ? formatDate(String(date)) : String(date)) : translate(row.status)}</span></div></article>; })}<style jsx>{`.mobile-financial-list{border-top:1px solid var(--border)}article{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:15px;padding:16px 2px;border-bottom:1px solid var(--border)}.mobile-main,.mobile-meta{display:flex;flex-direction:column;gap:5px}.mobile-main strong{font-size:14px}.mobile-main span,.mobile-meta span{font-size:11px;color:var(--muted)}.mobile-meta{text-align:right}.mobile-meta b{font-size:13px}.mobile-main .progress{margin-top:4px;max-width:180px}`}</style></div>; }

function InsightsBriefing({ data, loading, error, retry }: { data: Record<string, unknown>[]; loading: boolean; error: boolean; retry: () => void }) { return <div className="page insights-page"><div className="page-head"><div><h1>{data.length ? `${data.length} ${data.length === 1 ? "coisa merece" : "coisas merecem"} sua atenção` : "Insights"}</h1><p>Briefing financeiro com base nos registros atuais.</p></div></div>{loading ? <div className="skeleton" /> : error ? <div className="error-state" role="alert">Não foi possível carregar os insights. <button className="btn" onClick={retry}>Tentar novamente</button></div> : !data.length ? <div className="empty-state"><div><h2>Nenhuma condição relevante foi detectada</h2><p>Quando houver evidência suficiente, o Atlas mostrará aqui sinais e oportunidades — sem fingir análise.</p></div></div> : <ol>{data.map((item, index) => <li key={String(item.id ?? index)}><span className="number">{String(index + 1).padStart(2, "0")}</span><div><div className={`severity ${String(item.severity ?? "INFO").toLowerCase()}`}>{translate(item.severity ?? "INFO")}</div><h2>{String(item.title ?? "Análise financeira")}</h2><p>{String(item.description ?? item.message ?? "Com base nos dados registrados.")}</p><footer><span>{translate(item.category ?? item.type ?? "")}</span><span>{String(item.currency ?? "")}</span></footer></div></li>)}</ol>}<style jsx>{`.insights-page ol{list-style:none;margin:0;padding:0;border-top:1px solid var(--border)}.insights-page li{display:grid;grid-template-columns:72px minmax(0,1fr);gap:22px;padding:28px 0;border-bottom:1px solid var(--border)}.number{font-size:12px;font-weight:800;color:var(--atlas);font-variant-numeric:tabular-nums}.severity{font-size:10px;text-transform:uppercase;letter-spacing:.08em;font-weight:800;color:var(--information)}.severity.opportunity{color:var(--opportunity)}.severity.warning{color:var(--warning)}.severity.critical{color:var(--critical)}h2{font-size:clamp(21px,2.4vw,31px);letter-spacing:-.035em;margin:8px 0}p{color:var(--text-secondary);line-height:1.65;max-width:760px;margin:0}footer{display:flex;gap:18px;margin-top:16px;color:var(--muted);font-size:11px}@media(max-width:600px){.insights-page li{grid-template-columns:34px;gap:8px;padding:22px 0}}`}</style></div>; }

function CreateDialog({ title, fields, pending, close, submit, transfer }: { title: string; fields: Field[]; pending: boolean; close: () => void; submit: (value: Record<string, unknown>) => void; transfer: boolean }) { const [values, setValues] = useState<Record<string, string>>({}); const [error, setError] = useState(""); return <div className="overlay" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) close(); }}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header><div><h2 id="dialog-title">Novo registro em {title}</h2>{transfer && <p className="muted">Origem → destino, na mesma moeda.</p>}</div><button className="icon-button" aria-label="Fechar" onClick={close}><X /></button></header><form onSubmit={(event) => { event.preventDefault(); try { const body = Object.fromEntries(Object.entries(values).filter(([, value]) => value !== "").map(([key, value]) => [key, fields.find((field) => field.name === key)?.type === "money" ? normalizeMoneyInput(value) : value])); submit(body); } catch (caught) { setError(caught instanceof Error ? caught.message : "Dados inválidos"); } }}>{fields.map((field) => <div className={`field ${transfer && /fromAccount|toAccount/.test(field.name) ? "transfer-account" : ""}`} key={field.name}><label htmlFor={field.name}>{field.label}</label>{field.type === "select" ? <select id={field.name} required={field.required} value={values[field.name] ?? ""} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })}><option value="">Selecione</option>{field.options?.map((option) => <option key={option} value={option}>{translate(option)}</option>)}</select> : <input id={field.name} required={field.required} type={field.type === "date" ? "date" : "text"} inputMode={field.type === "money" ? "decimal" : undefined} value={values[field.name] ?? ""} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })} />}</div>)}{error && <p className="form-error" role="alert">{error}</p>}<footer><button type="button" className="btn" onClick={close}>Cancelar</button><button className="btn primary" disabled={pending}>{pending ? "Salvando…" : "Salvar"}</button></footer></form></section></div>; }

function ErrorPanel({ error, retry }: { error: Error; retry: () => void }) { const apiError = error instanceof ApiError ? error : null; return <div className="panel error-state" role="alert"><h2>{apiError?.status === 404 ? "Não encontrado" : "Não foi possível carregar"}</h2><p className="muted">{error.message}</p>{apiError?.body.requestId && <details><summary>Detalhes técnicos</summary><code>Request ID: {apiError.body.requestId}</code></details>}<button className="btn" onClick={retry}><RefreshCw /> Tentar novamente</button></div>; }
