import { Type } from "class-transformer";
import { IsBoolean, IsDateString, IsEnum, IsOptional, IsString, IsUUID, Matches, Max, MaxLength, Min, IsInt } from "class-validator";
export enum RecurringTypeDto { INCOME = "INCOME", EXPENSE = "EXPENSE" }
export enum RecurrenceKindDto { WEEKLY = "WEEKLY", MONTHLY = "MONTHLY", YEARLY = "YEARLY" }
export enum RecurringStatusDto { ACTIVE = "ACTIVE", PAUSED = "PAUSED", ENDED = "ENDED" }
export enum RecurringSortByDto { NEXT_OCCURRENCE_DATE = "nextOccurrenceDate", CREATED_AT = "createdAt", AMOUNT = "amount", RECURRENCE_KIND = "recurrenceKind" }
export enum SortOrderDto { ASC = "asc", DESC = "desc" }
const money = /^(?!0(?:\.0{1,4})?$)\d{1,15}(?:\.\d{1,4})?$/; const currency = /^[A-Z]{3}$/;
export class CreateRecurringTransactionDto { @IsUUID() accountId!: string; @IsOptional() @IsUUID() categoryId?: string; @IsEnum(RecurringTypeDto) type!: RecurringTypeDto; @IsEnum(RecurrenceKindDto) recurrenceKind!: RecurrenceKindDto; @IsString() @MaxLength(120) name!: string; @IsOptional() @IsString() @MaxLength(180) description?: string; @IsString() @Matches(money) amount!: string; @IsOptional() @IsString() @Matches(currency) currency?: string; @IsDateString() startDate!: string; @IsOptional() @IsDateString() endDate?: string; @IsOptional() @IsBoolean() isSubscription?: boolean; @IsOptional() @IsString() @MaxLength(120) providerName?: string; }
export class UpdateRecurringTransactionDto { @IsOptional() @IsUUID() accountId?: string; @IsOptional() @IsUUID() categoryId?: string | null; @IsOptional() @IsEnum(RecurringTypeDto) type?: RecurringTypeDto; @IsOptional() @IsEnum(RecurrenceKindDto) recurrenceKind?: RecurrenceKindDto; @IsOptional() @IsString() @MaxLength(120) name?: string; @IsOptional() @IsString() @MaxLength(180) description?: string | null; @IsOptional() @IsString() @Matches(money) amount?: string; @IsOptional() @IsString() @Matches(currency) currency?: string; @IsOptional() @IsDateString() startDate?: string; @IsOptional() @IsDateString() endDate?: string | null; @IsOptional() @IsBoolean() isSubscription?: boolean; @IsOptional() @IsString() @MaxLength(120) providerName?: string | null; }
export class ListRecurringTransactionsDto { @IsOptional() @IsEnum(RecurringStatusDto) status?: RecurringStatusDto; @IsOptional() @IsEnum(RecurringTypeDto) type?: RecurringTypeDto; @IsOptional() @IsEnum(RecurrenceKindDto) recurrenceKind?: RecurrenceKindDto; @IsOptional() @IsUUID() accountId?: string; @IsOptional() @IsUUID() categoryId?: string; @IsOptional() @IsString() @Matches(currency) currency?: string; @IsOptional() @IsDateString() nextStartDate?: string; @IsOptional() @IsDateString() nextEndDate?: string; @IsOptional() @IsString() @MaxLength(120) search?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) page?: number; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) pageSize?: number; @IsOptional() @IsEnum(RecurringSortByDto) sortBy?: RecurringSortByDto; @IsOptional() @IsEnum(SortOrderDto) sortOrder?: SortOrderDto; }
