import { Prisma } from "@prisma/client";
import { Test } from "@nestjs/testing";
import { AuditService } from "../audit/audit.service.js";
import { PrismaService } from "../prisma/prisma.service.js";
import { ImportsService } from "./imports.service.js";

const userId="00000000-0000-4000-8000-000000000001", otherUserId="00000000-0000-4000-8000-000000000002", batchId="00000000-0000-4000-8000-000000000010", accountId="00000000-0000-4000-8000-000000000020", itemId="00000000-0000-4000-8000-000000000030";
describe("ImportsService confirmation",()=>{
 let service:ImportsService; let calls=0; const item={id:itemId,inferredType:"INCOME",fingerprint:"f",amount:new Prisma.Decimal("10"),rawDescription:"Salary",transactionDate:new Date("2026-08-01"),externalId:null};
 const transaction={findFirst:jest.fn<Promise<{id:string}|null>,[]>(()=>Promise.resolve(null)),create:jest.fn(()=>Promise.resolve({id:"00000000-0000-4000-8000-000000000040"}))};
 const client={importBatch:{findFirst:jest.fn<Promise<{id:string;accountId:string}|null>,[]>(()=>Promise.resolve({id:batchId,accountId})),update:jest.fn(()=>Promise.resolve(undefined))},importItem:{findMany:jest.fn(()=>Promise.resolve([item])),update:jest.fn(()=>Promise.resolve(undefined)),count:jest.fn(()=>Promise.resolve(1))},transaction,account:{update:jest.fn(()=>Promise.resolve(undefined))}};
 const database={$transaction:jest.fn((callback:(value:typeof client)=>Promise<unknown>)=>{calls+=1;return callback(client);})}; const audit={record:jest.fn(()=>Promise.resolve(undefined))};
 beforeEach(async()=>{calls=0;jest.clearAllMocks();client.importBatch.findFirst.mockImplementation(()=>Promise.resolve({id:batchId,accountId}));client.importItem.findMany.mockImplementation(()=>Promise.resolve([item]));client.importItem.count.mockImplementation(()=>Promise.resolve(1));transaction.findFirst.mockImplementation(()=>Promise.resolve(null));const module=await Test.createTestingModule({providers:[ImportsService,{provide:PrismaService,useValue:database},{provide:AuditService,useValue:audit}]}).compile();service=module.get(ImportsService);});
 it("creates, links and balances an owned ready batch in one transaction",async()=>{await expect(service.confirm(userId,batchId)).resolves.toEqual({imported:1,duplicates:1});expect(calls).toBe(1);expect(transaction.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({userId,accountId,importItemId:itemId})}));expect(client.account.update).toHaveBeenCalled();expect(audit.record).toHaveBeenCalledWith(expect.objectContaining({eventType:"IMPORT_COMPLETED"}));});
 it("rejects repeated confirmation after the batch is no longer reviewable",async()=>{client.importBatch.findFirst.mockImplementation(()=>Promise.resolve(null));await expect(service.confirm(userId,batchId)).rejects.toMatchObject({response:expect.objectContaining({code:"IMPORT_NOT_READY"})});expect(transaction.create).not.toHaveBeenCalled();});
 it("marks an existing fingerprint as duplicate without changing balance",async()=>{transaction.findFirst.mockImplementation(()=>Promise.resolve({id:"00000000-0000-4000-8000-000000000050"}));await service.confirm(userId,batchId);expect(transaction.create).not.toHaveBeenCalled();expect(client.account.update).not.toHaveBeenCalled();expect(client.importItem.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({status:"DUPLICATE"})}));});
 it("keeps caller ownership in the transaction lookup",async()=>{await service.confirm(otherUserId,batchId);expect(client.importBatch.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:batchId,userId:otherUserId})}));});
 it("propagates a transaction-create failure without finalizing or auditing",async()=>{transaction.create.mockImplementation(()=>Promise.reject(new Error("write failure")));await expect(service.confirm(userId,batchId)).rejects.toThrow("write failure");expect(client.importBatch.update).not.toHaveBeenCalled();expect(audit.record).not.toHaveBeenCalled();});
});
