import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { createHash } from "node:crypto";
import { Prisma } from "@prisma/client";
import { AuditService } from "../audit/audit.service.js";
import { PrismaService } from "../prisma/prisma.service.js";
import { ImportSourceDto, type ImportMappingDto, type ListImportItemsDto, type ListImportsDto, type UploadImportDto } from "./dto/imports.dto.js";
const MAX_BYTES=10*1024*1024, MAX_ROWS=10000, amount=/^-?\d{1,15}(?:\.\d{1,4})?$/;
type Row={line:number;date:Date;description:string;amount:Prisma.Decimal;type:"INCOME"|"EXPENSE";externalId:string|null;fingerprint:string};
const normalize=(value:string)=>value.trim().toLowerCase().replace(/\s+/g," ");
@Injectable() export class ImportsService {
 constructor(@Inject(PrismaService) private readonly prisma:PrismaService,@Inject(AuditService) private readonly audit:AuditService){}
 async upload(userId:string,dto:UploadImportDto){const bytes=Buffer.from(dto.contentBase64,"base64");if(!bytes.length||bytes.length>MAX_BYTES)throw new BadRequestException({code:"INVALID_FILE",message:"Invalid file"});const name=dto.fileName.replace(/[\\/]/g,"_");if(!/\.(csv|ofx|qfx)$/i.test(name))throw new BadRequestException({code:"UNSUPPORTED_FILE",message:"Unsupported file"});const rows=dto.sourceType===ImportSourceDto.CSV?this.csv(bytes.toString("utf8")):this.ofx(bytes.toString("utf8"));if(rows.length>MAX_ROWS)throw new BadRequestException({code:"TOO_MANY_ROWS",message:"Too many rows"});const account=await this.prisma.account.findFirst({where:{id:dto.accountId,userId,deletedAt:null,status:"ACTIVE"},select:{id:true,currency:true}});if(!account)throw new NotFoundException({code:"ACCOUNT_NOT_FOUND",message:"Account not found"});const hash=createHash("sha256").update(bytes).digest("hex");const batch=await this.prisma.importBatch.create({data:{userId,accountId:account.id,sourceType:dto.sourceType,fileHash:hash,fileSizeBytes:bytes.length,originalFileName:name,status:"REVIEW_REQUIRED",totalRows:rows.length,parsedRows:rows.length,failedRows:0,duplicateRows:0,parserVersion:"1"}});await this.prisma.importItem.createMany({data:rows.map(row=>({importBatchId:batch.id,userId,accountId:account.id,rowNumber:row.line,externalId:row.externalId,rawDescription:row.description,normalizedDescription:normalize(row.description),amount:row.amount,inferredType:row.type,errorMessage:null,fingerprint:row.fingerprint,status:"READY",transactionDate:row.date}))});return this.detail(userId,batch.id);}
 async detail(userId:string,id:string){const batch=await this.prisma.importBatch.findFirst({where:{id,userId},include:{importItems:{select:{id:true,rowNumber:true,rawDescription:true,amount:true,inferredType:true,status:true,errorMessage:true,transactionDate:true}}}});if(!batch)throw new NotFoundException({code:"IMPORT_NOT_FOUND",message:"Import not found"});return {id:batch.id,status:batch.status,sourceType:batch.sourceType,totalRows:batch.totalRows,items:batch.importItems.slice(0,50).map(i=>({...i,amount:i.amount.toString()}))};}
 async list(userId:string,query:ListImportsDto){const page=query.page??1,pageSize=query.pageSize??20,where={userId,accountId:query.accountId,status:query.status,sourceType:query.sourceType};const [rows,total]=await this.prisma.$transaction([this.prisma.importBatch.findMany({where,orderBy:[{createdAt:"desc"},{id:"desc"}],skip:(page-1)*pageSize,take:pageSize}),this.prisma.importBatch.count({where})]);return {data:rows.map(row=>({id:row.id,status:row.status,sourceType:row.sourceType,totalRows:row.totalRows,createdAt:row.createdAt})),meta:{page,pageSize,total,totalPages:Math.ceil(total/pageSize)}};}
 async items(userId:string,id:string,query:ListImportItemsDto){await this.owned(userId,id);const page=query.page??1,pageSize=query.pageSize??20,where={importBatchId:id,userId,status:query.status};const [rows,total]=await this.prisma.$transaction([this.prisma.importItem.findMany({where,orderBy:[{rowNumber:"asc"},{id:"asc"}],skip:(page-1)*pageSize,take:pageSize,select:{id:true,rowNumber:true,rawDescription:true,amount:true,inferredType:true,status:true,errorMessage:true,transactionDate:true}}),this.prisma.importItem.count({where})]);return {data:rows.map(row=>({...row,amount:row.amount.toString()})),meta:{page,pageSize,total,totalPages:Math.ceil(total/pageSize)}};}
 async mapping(userId:string,id:string,dto:ImportMappingDto){const batch=await this.owned(userId,id);if(batch.status!=="REVIEW_REQUIRED")throw new ConflictException({code:"IMPORT_NOT_MAPPABLE",message:"Import cannot be mapped"});if(!dto.dateColumn||!dto.descriptionColumn||!dto.amountColumn)throw new BadRequestException({code:"INVALID_MAPPING",message:"Date, description and amount columns are required"});await this.prisma.importBatch.update({where:{id},data:{metadata:{mapping:{dateColumn:dto.dateColumn,descriptionColumn:dto.descriptionColumn,amountColumn:dto.amountColumn,dateFormat:dto.dateFormat??null}}}});await this.audit.record({action:"import.mapping.update",actorUserId:userId,entityId:id,entityType:"import_batch",eventType:"ENTITY_UPDATED",userId});return this.detail(userId,id);}
async confirm(userId:string,id:string){return this.prisma.$transaction(async tx=>{const batch=await tx.importBatch.findFirst({where:{id,userId,status:"REVIEW_REQUIRED"}});if(!batch)throw new ConflictException({code:"IMPORT_NOT_READY",message:"Import is not ready"});const items=await tx.importItem.findMany({where:{importBatchId:id,userId,status:"READY"}});for(const item of items){if(item.inferredType==="UNKNOWN"){await tx.importItem.update({where:{id:item.id},data:{status:"FAILED",errorMessage:"Transaction type is unknown"}});continue;}const duplicate=await tx.transaction.findFirst({where:{userId,accountId:batch.accountId,fingerprint:item.fingerprint,deletedAt:null}});if(duplicate){await tx.importItem.update({where:{id:item.id},data:{status:"DUPLICATE",matchedTransactionId:duplicate.id}});continue;}const record=await tx.transaction.create({data:{userId,accountId:batch.accountId,importItemId:item.id,type:item.inferredType,status:"CONFIRMED",description:item.rawDescription,amount:item.amount,transactionDate:item.transactionDate,source:batch.sourceType,externalReference:item.externalId,fingerprint:item.fingerprint}});await tx.account.update({where:{id:batch.accountId},data:{currentBalance:{[item.inferredType==="INCOME"?"increment":"decrement"]:item.amount}}});await tx.importItem.update({where:{id:item.id},data:{status:"IMPORTED",matchedTransactionId:record.id}});}const imported=await tx.importItem.count({where:{importBatchId:id,status:"IMPORTED"}}),duplicates=await tx.importItem.count({where:{importBatchId:id,status:"DUPLICATE"}});await tx.importBatch.update({where:{id},data:{status:"IMPORTED",importedRows:imported,duplicateRows:duplicates,completedAt:new Date()}});return {imported,duplicates};}).then(async result=>{await this.audit.record({action:"import.complete",actorUserId:userId,entityId:id,entityType:"import_batch",eventType:"IMPORT_COMPLETED",userId,metadata:result});return result;});}
 async cancel(userId:string,id:string){const batch=await this.prisma.importBatch.updateMany({where:{id,userId,status:{in:["UPLOADED","PARSED","REVIEW_REQUIRED","FAILED"]}},data:{status:"CANCELLED"}});if(!batch.count)throw new ConflictException({code:"IMPORT_NOT_CANCELLABLE",message:"Import cannot be cancelled"});await this.audit.record({action:"import.cancel",actorUserId:userId,entityId:id,entityType:"import_batch",eventType:"ENTITY_UPDATED",userId});return {success:true};}
 private async owned(userId:string,id:string){const batch=await this.prisma.importBatch.findFirst({where:{id,userId}});if(!batch)throw new NotFoundException({code:"IMPORT_NOT_FOUND",message:"Import not found"});return batch;}
 private csv(input:string):Row[]{const lines=input.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new BadRequestException({code:"INVALID_CSV",message:"CSV requires header and rows"});const delimiter=input.includes(";")?";":input.includes("\t")?"\t":",";const headers=lines[0]!.split(delimiter).map(normalize);const dateIndex=headers.indexOf("date"),descriptionIndex=headers.findIndex(x=>["description","memo"].includes(x)),amountIndex=headers.indexOf("amount");if(dateIndex<0||descriptionIndex<0||amountIndex<0)throw new BadRequestException({code:"CSV_MAPPING_REQUIRED",message:"CSV must contain date, description and amount"});return lines.slice(1).map((line,index)=>{const parts=line.split(delimiter);const raw=parts[amountIndex]?.trim()??"";if(!amount.test(raw))throw new BadRequestException({code:"INVALID_AMOUNT",message:"Invalid amount"});const value=new Prisma.Decimal(raw),date=new Date(parts[dateIndex]??"");const descriptionValue=parts[descriptionIndex];if(Number.isNaN(date.getTime())||!descriptionValue?.trim())throw new BadRequestException({code:"INVALID_ROW",message:"Invalid row"});const description=descriptionValue.trim(),externalId=null;return {line:index+2,date,description,amount:value.abs(),type:value.isNegative()?"EXPENSE":"INCOME",externalId,fingerprint:this.fingerprint(description,value.abs(),date,externalId)};});}
 private ofx(input:string):Row[]{if(/<!ENTITY|<!DOCTYPE/i.test(input))throw new BadRequestException({code:"INVALID_OFX",message:"Invalid OFX"});const blocks=input.match(/<STMTTRN>[\s\S]*?<\/STMTTRN>|<STMTTRN>[\s\S]*?(?=<STMTTRN>|<LEDGERBAL>|$)/gi)??[];if(!blocks.length)throw new BadRequestException({code:"INVALID_OFX",message:"OFX has no transactions"});return blocks.map((block,index)=>{const get=(tag:string)=>new RegExp(`<${tag}>([^<\r\n]+)`,"i").exec(block)?.[1]?.trim()??"";const raw=get("TRNAMT"),dateText=get("DTPOSTED").slice(0,8),description=get("NAME")||get("MEMO"),externalId=get("FITID")||null;if(!amount.test(raw)||!/^\d{8}$/.test(dateText)||!description)throw new BadRequestException({code:"INVALID_OFX",message:"Invalid OFX transaction"});const value=new Prisma.Decimal(raw),date=new Date(Date.UTC(Number(dateText.slice(0,4)),Number(dateText.slice(4,6))-1,Number(dateText.slice(6,8))));return {line:index+1,date,description,amount:value.abs(),type:value.isNegative()?"EXPENSE":"INCOME",externalId,fingerprint:this.fingerprint(description,value.abs(),date,externalId)};});}
 private fingerprint(description:string,amount:Prisma.Decimal,date:Date,externalId:string|null){return createHash("sha256").update(["v1",externalId??"",normalize(description),amount.toFixed(4),date.toISOString().slice(0,10)].join("|")).digest("hex");}
}
