import { BadRequestException } from "@nestjs/common";
import { createHash } from "node:crypto";
import { Prisma } from "@prisma/client";
export type ParsedImportRow={line:number;date:Date;description:string;amount:Prisma.Decimal;type:"INCOME"|"EXPENSE";externalId:string|null;fingerprint:string};
const amount=/^-?\d{1,15}(?:\.\d{1,4})?$/;
const normalize=(value:string)=>value.trim().toLowerCase().replace(/\s+/g," ");
export function importFingerprint(description:string,value:Prisma.Decimal,date:Date,externalId:string|null):string{return createHash("sha256").update(["v1",externalId??"",normalize(description),value.toFixed(4),date.toISOString().slice(0,10)].join("|")).digest("hex");}
export function parseCsv(input:string):ParsedImportRow[]{const lines=input.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new BadRequestException({code:"INVALID_CSV",message:"CSV requires header and rows"});const delimiter=input.includes(";")?";":input.includes("\t")?"\t":",";const headers=lines[0]!.split(delimiter).map(normalize);const dateIndex=headers.indexOf("date"),descriptionIndex=headers.findIndex(value=>["description","memo"].includes(value)),amountIndex=headers.indexOf("amount");if(dateIndex<0||descriptionIndex<0||amountIndex<0)throw new BadRequestException({code:"CSV_MAPPING_REQUIRED",message:"CSV must contain date, description and amount"});return lines.slice(1).map((line,index)=>{const parts=line.split(delimiter),raw=parts[amountIndex]?.trim()??"",descriptionValue=parts[descriptionIndex];if(!amount.test(raw))throw new BadRequestException({code:"INVALID_AMOUNT",message:"Invalid amount"});const signed=new Prisma.Decimal(raw),date=new Date(parts[dateIndex]??"");if(Number.isNaN(date.getTime())||!descriptionValue?.trim())throw new BadRequestException({code:"INVALID_ROW",message:"Invalid row"});const description=descriptionValue.trim(),externalId=null,value=signed.abs();return {line:index+2,date,description,amount:value,type:signed.isNegative()?"EXPENSE":"INCOME",externalId,fingerprint:importFingerprint(description,value,date,externalId)};});}
export function parseOfx(input:string):ParsedImportRow[]{if(/<!ENTITY|<!DOCTYPE/i.test(input))throw new BadRequestException({code:"INVALID_OFX",message:"Invalid OFX"});const blocks=input.match(/<STMTTRN>[\s\S]*?<\/STMTTRN>|<STMTTRN>[\s\S]*?(?=<STMTTRN>|<LEDGERBAL>|$)/gi)??[];if(!blocks.length)throw new BadRequestException({code:"INVALID_OFX",message:"OFX has no transactions"});return blocks.map((block,index)=>{const get=(tag:string)=>new RegExp(`<${tag}>([^<\r\n]+)`,"i").exec(block)?.[1]?.trim()??"",raw=get("TRNAMT"),dateText=get("DTPOSTED").slice(0,8),description=get("NAME")||get("MEMO"),externalId=get("FITID")||null;if(!amount.test(raw)||!/^\d{8}$/.test(dateText)||!description)throw new BadRequestException({code:"INVALID_OFX",message:"Invalid OFX transaction"});const signed=new Prisma.Decimal(raw),date=new Date(Date.UTC(Number(dateText.slice(0,4)),Number(dateText.slice(4,6))-1,Number(dateText.slice(6,8)))),value=signed.abs();return {line:index+1,date,description,amount:value,type:signed.isNegative()?"EXPENSE":"INCOME",externalId,fingerprint:importFingerprint(description,value,date,externalId)};});}
