import { BadRequestException, Inject, Injectable } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service.js";
import { serializeDecimal } from "../financial/money.js";
import { CashFlowGroupDto, type CashFlowDto, type DashboardPeriodDto, type RecentTransactionsDto } from "./dto/dashboard.dto.js";

type Period = { start: Date; end: Date };
type AggregateRow = { type: string; _sum: { amount: Prisma.Decimal | null }; _count?: { _all: number } };
export function budgetUsage(limit: Prisma.Decimal, spent: Prisma.Decimal): { remaining: Prisma.Decimal; percentage: string; status: "NORMAL" | "ALERT" | "EXCEEDED" } { const usage = limit.isZero() ? new Prisma.Decimal(0) : spent.dividedBy(limit).mul(100); return { remaining: limit.minus(spent), percentage: usage.toFixed(2), status: usage.greaterThanOrEqualTo(100) ? "EXCEEDED" : usage.greaterThanOrEqualTo(80) ? "ALERT" : "NORMAL" }; }
@Injectable()
export class DashboardService {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  async overview(userId: string, query: DashboardPeriodDto) {
    const period = this.period(query); const previous = this.previous(period); const filter = this.transactionWhere(userId, period, query);
    const [balances, current, prior, accountsCount, activeGoals, upcomingRecurringCount] = await Promise.all([
      this.prisma.account.groupBy({ by: ["currency"], where: { userId, deletedAt: null, status: { not: "DELETED" } }, _sum: { currentBalance: true } }),
      this.prisma.transaction.groupBy({ by: ["type"], where: filter, _sum: { amount: true }, _count: { _all: true } }),
      this.prisma.transaction.groupBy({ by: ["type"], where: this.transactionWhere(userId, previous, query), _sum: { amount: true } }),
      this.prisma.account.count({ where: { userId, deletedAt: null, status: { not: "DELETED" } } }),
      this.prisma.goal.count({ where: { userId, deletedAt: null, status: "ACTIVE" } }),
      this.prisma.recurringTransaction.count({ where: { userId, deletedAt: null, status: "ACTIVE", nextOccurrenceDate: { gte: this.today() } } })
    ]);
    const values = this.cash(current), before = this.cash(prior);
    return { period: { startDate: period.start, endDate: period.end, currency: query.currency ?? null }, balances: balances.map(item => ({ currency: item.currency, amount: serializeDecimal(item._sum.currentBalance ?? new Prisma.Decimal(0)) })), income: values.income, expenses: values.expenses, netCashFlow: values.net, transactionsCount: values.count, previousPeriod: before, variation: { incomePercentage: this.variation(values.income, before.income), expensesPercentage: this.variation(values.expenses, before.expenses), netCashFlowPercentage: this.variation(values.net, before.net) }, accountsCount, activeGoals, upcomingRecurringCount };
  }
  async cashFlow(userId: string, query: CashFlowDto) { const period = this.period(query, 6); const group = query.groupBy ?? CashFlowGroupDto.MONTH; const rows = await this.prisma.$queryRaw<{ period: string; currency: string; income: Prisma.Decimal; expenses: Prisma.Decimal }[]>(Prisma.sql`SELECT ${group === CashFlowGroupDto.DAY ? Prisma.sql`to_char(t.transaction_date, 'YYYY-MM-DD')` : Prisma.sql`to_char(t.transaction_date, 'YYYY-MM')`} AS period, a.currency, COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS income, COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount ELSE 0 END), 0) AS expenses FROM transactions t JOIN accounts a ON a.id = t.account_id WHERE t.user_id = ${userId}::uuid AND t.deleted_at IS NULL AND t.status = 'confirmed' AND t.transaction_date >= ${period.start} AND t.transaction_date <= ${period.end} AND (${query.currency ?? null}::text IS NULL OR a.currency = ${query.currency ?? null}) AND (${query.accountId ?? null}::uuid IS NULL OR t.account_id = ${query.accountId ?? null}::uuid) GROUP BY 1, 2 ORDER BY 1 ASC, 2 ASC`); return { period: { startDate: period.start, endDate: period.end }, data: rows.map(row => ({ period: row.period, currency: row.currency, income: serializeDecimal(row.income), expenses: serializeDecimal(row.expenses), net: serializeDecimal(row.income.minus(row.expenses)) })) }; }
  async categories(userId: string, query: DashboardPeriodDto) { const period = this.period(query); const rows = await this.prisma.transaction.groupBy({ by: ["categoryId", "type"], where: { ...this.transactionWhere(userId, period, query), type: { in: ["INCOME", "EXPENSE"] } }, _sum: { amount: true }, _count: { _all: true }, orderBy: { _sum: { amount: "desc" } } }); const ids = rows.flatMap(row => row.categoryId ? [row.categoryId] : []); const categories = await this.prisma.category.findMany({ where: { id: { in: ids }, deletedAt: null }, select: { id: true, name: true, color: true, icon: true } }); const lookup = new Map(categories.map(category => [category.id, category])); const totals = new Map<string, Prisma.Decimal>(); for (const row of rows) totals.set(row.type, (totals.get(row.type) ?? new Prisma.Decimal(0)).plus(row._sum.amount ?? 0)); return { period: { startDate: period.start, endDate: period.end }, data: rows.map(row => { const amount = row._sum.amount ?? new Prisma.Decimal(0), total = totals.get(row.type) ?? new Prisma.Decimal(0), category = row.categoryId ? lookup.get(row.categoryId) : undefined; return { type: row.type, categoryId: row.categoryId, categoryName: category?.name ?? "Uncategorized", color: category?.color ?? null, icon: category?.icon ?? null, amount: serializeDecimal(amount), percentage: total.isZero() ? null : amount.dividedBy(total).mul(100).toFixed(2), transactionsCount: row._count._all }; }) }; }
  async accounts(userId: string, query: DashboardPeriodDto) { const records = await this.prisma.account.findMany({ where: { userId, deletedAt: null, status: { not: "DELETED" }, currency: query.currency }, select: { id: true, name: true, type: true, currency: true, currentBalance: true, status: true }, orderBy: [{ currency: "asc" }, { currentBalance: "desc" }, { id: "asc" }] }); const totals = new Map<string, Prisma.Decimal>(); for (const item of records) totals.set(item.currency, (totals.get(item.currency) ?? new Prisma.Decimal(0)).plus(item.currentBalance)); return { data: records.map(item => ({ ...item, currentBalance: serializeDecimal(item.currentBalance), percentageOfCurrency: totals.get(item.currency)?.isZero() ? null : item.currentBalance.dividedBy(totals.get(item.currency)!).mul(100).toFixed(2) })) }; }
  async budgets(userId: string, query: DashboardPeriodDto) { const date = this.period(query).start; const month = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1)), nextMonth = new Date(Date.UTC(month.getUTCFullYear(), month.getUTCMonth() + 1, 1)); const records = await this.prisma.monthlyBudget.findMany({ where: { userId, deletedAt: null, month, currency: query.currency }, select: { id: true, currency: true, totalLimit: true, status: true, budgetCategoryLimits: { select: { id: true, categoryId: true, limitAmount: true, category: { select: { name: true } } } } } }); const grouped = await Promise.all(records.map(record => this.prisma.transaction.groupBy({ by: ["categoryId"], _sum: { amount: true }, where: { userId, categoryId: { in: record.budgetCategoryLimits.map(limit => limit.categoryId) }, deletedAt: null, status: "CONFIRMED", type: "EXPENSE", transactionDate: { gte: month, lt: nextMonth }, account: { currency: record.currency } } })));
    const totals = new Map<string, { budgeted: Prisma.Decimal; spent: Prisma.Decimal; normal: number; alert: number; exceeded: number }>(); const data = records.map((record, index) => { const spentByCategory = new Map((grouped[index] ?? []).map(row => [row.categoryId, row._sum.amount ?? new Prisma.Decimal(0)])); const limits = record.budgetCategoryLimits.map(limit => { const spent = spentByCategory.get(limit.categoryId) ?? new Prisma.Decimal(0), usage = budgetUsage(limit.limitAmount, spent), status = usage.status; const summary = totals.get(record.currency) ?? { budgeted: new Prisma.Decimal(0), spent: new Prisma.Decimal(0), normal: 0, alert: 0, exceeded: 0 }; summary.budgeted = summary.budgeted.plus(limit.limitAmount); summary.spent = summary.spent.plus(spent); if (status === "NORMAL") summary.normal += 1; else if (status === "ALERT") summary.alert += 1; else summary.exceeded += 1; totals.set(record.currency, summary); return { id: limit.id, categoryId: limit.categoryId, categoryName: limit.category.name, limitAmount: serializeDecimal(limit.limitAmount), spentAmount: serializeDecimal(spent), remainingAmount: serializeDecimal(usage.remaining), usagePercentage: usage.percentage, status }; }); return { id: record.id, currency: record.currency, totalLimit: record.totalLimit ? serializeDecimal(record.totalLimit) : null, status: record.status, categoryLimits: limits }; }); return { month, data, totals: [...totals.entries()].map(([currency, value]) => ({ currency, totalBudgeted: serializeDecimal(value.budgeted), totalSpent: serializeDecimal(value.spent), totalRemaining: serializeDecimal(value.budgeted.minus(value.spent)), normalCount: value.normal, alertCount: value.alert, exceededCount: value.exceeded })) }; }
  async goals(userId: string, query: DashboardPeriodDto) { const records = await this.prisma.goal.findMany({ where: { userId, deletedAt: null, status: "ACTIVE", currency: query.currency }, select: { id: true, name: true, targetAmount: true, currentAmount: true, targetDate: true, currency: true, priority: true, status: true }, orderBy: [{ targetDate: "asc" }, { id: "asc" }], take: 5 }); return { data: records.map(item => ({ ...item, targetAmount: serializeDecimal(item.targetAmount), currentAmount: serializeDecimal(item.currentAmount), remainingAmount: serializeDecimal(Prisma.Decimal.max(new Prisma.Decimal(0), item.targetAmount.minus(item.currentAmount))), progressPercentage: item.currentAmount.dividedBy(item.targetAmount).mul(100).toFixed(2) })) }; }
  async recurring(userId: string, query: DashboardPeriodDto) { const records = await this.prisma.recurringTransaction.findMany({ where: { userId, deletedAt: null, status: "ACTIVE", currency: query.currency, nextOccurrenceDate: { gte: this.today() } }, select: { id: true, name: true, description: true, type: true, amount: true, currency: true, recurrenceKind: true, nextOccurrenceDate: true, account: { select: { id: true, name: true } }, category: { select: { id: true, name: true } } }, orderBy: [{ nextOccurrenceDate: "asc" }, { id: "asc" }], take: 10 }); return { data: records.map(item => ({ ...item, amount: serializeDecimal(item.amount) })) }; }
  async recentTransactions(userId: string, query: RecentTransactionsDto) { const limit = this.limit(query.limit); const records = await this.prisma.transaction.findMany({ where: { userId, deletedAt: null, status: { in: ["CONFIRMED", "PENDING", "IGNORED"] }, accountId: query.accountId, type: query.type, account: query.currency ? { currency: query.currency } : undefined }, select: { id: true, type: true, status: true, description: true, amount: true, transactionDate: true, source: true, account: { select: { id: true, name: true, currency: true } }, category: { select: { id: true, name: true } } }, orderBy: [{ transactionDate: "desc" }, { id: "desc" }], take: limit }); return { data: records.map(item => ({ ...item, amount: serializeDecimal(item.amount) })) }; }
  private transactionWhere(userId: string, period: Period, query: DashboardPeriodDto): Prisma.TransactionWhereInput { return { userId, deletedAt: null, status: "CONFIRMED", accountId: query.accountId, transactionDate: { gte: period.start, lte: period.end }, account: query.currency ? { currency: query.currency } : undefined, type: { in: ["INCOME", "EXPENSE", "ADJUSTMENT"] } }; }
  private cash(rows: readonly AggregateRow[]) { const get = (type: string) => rows.find(row => row.type === type)?._sum.amount ?? new Prisma.Decimal(0); const income = get("INCOME").plus(get("ADJUSTMENT")), expenses = get("EXPENSE"); return { income: serializeDecimal(income), expenses: serializeDecimal(expenses), net: serializeDecimal(income.minus(expenses)), count: rows.reduce((total, row) => total + (row._count?._all ?? 0), 0) }; }
  private variation(current: string, previous: string): string | null { const before = new Prisma.Decimal(previous); return before.isZero() ? null : new Prisma.Decimal(current).minus(before).dividedBy(before.abs()).mul(100).toFixed(2); }
  private period(query: DashboardPeriodDto, months = 1): Period { const now = new Date(); const fallbackStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - months + 1, 1)); const fallbackEnd = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 0, 23, 59, 59, 999)); const start = query.startDate ? this.date(query.startDate) : fallbackStart, end = query.endDate ? this.date(query.endDate, true) : fallbackEnd; if (end < start) throw new BadRequestException({ code: "INVALID_DATE_RANGE", message: "Invalid date range" }); return { start, end }; }
  private previous(period: Period): Period { const duration = period.end.getTime() - period.start.getTime() + 1; return { start: new Date(period.start.getTime() - duration), end: new Date(period.start.getTime() - 1) }; }
  private date(value: string, end = false): Date { const date = new Date(value); if (Number.isNaN(date.getTime())) throw new BadRequestException({ code: "INVALID_DATE", message: "Invalid date" }); if (end && /^\d{4}-\d{2}-\d{2}$/.test(value)) date.setUTCHours(23, 59, 59, 999); return date; }
  private today(): Date { const now = new Date(); return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())); }
  private limit(value: number | undefined): number { const candidate = value ?? 10, parsed = typeof candidate === "number" ? candidate : Number.parseInt(String(candidate), 10); if (!Number.isInteger(parsed) || parsed < 1 || parsed > 50) throw new BadRequestException({ code: "INVALID_LIMIT", message: "Invalid limit" }); return parsed; }
}
