import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma } from "@prisma/client";

import { AuditService } from "../audit/audit.service.js";
import { FINANCIAL_DATABASE, type FinancialDatabasePort } from "../financial/financial-database.port.js";
import { applyBalanceDelta, type DatabaseTransaction, serializeDecimal } from "../financial/money.js";
import type { CreateTransactionDto, UpdateTransactionDto } from "./dto/transaction.dto.js";
import { ListTransactionsDto } from "./dto/list-transactions.dto.js";

const transactionSelect = { id: true, accountId: true, categoryId: true, type: true, status: true, description: true, amount: true, transactionDate: true, postedAt: true, merchantName: true, notes: true, createdAt: true, updatedAt: true } satisfies Prisma.TransactionSelect;
const money = /^(?!0(?:\.0{1,4})?$)\d{1,15}(?:\.\d{1,4})?$/;
type TransactionRecord = Prisma.TransactionGetPayload<{ select: typeof transactionSelect }>;
export type TransactionResponse = Omit<TransactionRecord, "amount"> & { amount: string };
export interface TransactionListResponse { data: TransactionResponse[]; meta: { page: number; pageSize: number; total: number; totalPages: number }; }

function present(record: TransactionRecord): TransactionResponse { return { ...record, amount: serializeDecimal(record.amount) }; }
function assertAmount(value: string): void { if (!money.test(value)) throw new BadRequestException({ code: "INVALID_AMOUNT", message: "Invalid amount" }); }
function pagination(value: number | undefined, fallback: number, maximum: number): number { const candidate = value ?? fallback; const parsed = typeof candidate === "number" ? candidate : Number.parseInt(String(candidate), 10); if (!Number.isInteger(parsed) || parsed < 1 || parsed > maximum) throw new BadRequestException({ code: "INVALID_PAGINATION", message: "Invalid pagination" }); return parsed; }

@Injectable()
export class TransactionsService {
  constructor(@Inject(FINANCIAL_DATABASE) private readonly prisma: FinancialDatabasePort, @Inject(AuditService) private readonly audit: AuditService) {}
  async create(userId: string, dto: CreateTransactionDto): Promise<TransactionResponse> { assertAmount(dto.amount); return this.prisma.$transaction(async transaction => { await this.validateReferences(transaction, userId, dto.accountId, dto.categoryId, dto.type); const record = await transaction.transaction.create({ data: { accountId: dto.accountId, amount: new Prisma.Decimal(dto.amount), categoryId: dto.categoryId, description: dto.description.trim(), merchantName: dto.merchantName, notes: dto.notes, source: "MANUAL", status: dto.status ?? "CONFIRMED", transactionDate: new Date(dto.transactionDate), type: dto.type, userId }, select: transactionSelect }); if (record.status === "CONFIRMED") await applyBalanceDelta(transaction, record.accountId, record.type, record.amount); return present(record); }); }
  async list(userId: string, query: ListTransactionsDto): Promise<TransactionListResponse> { const page = pagination(query.page, 1, Number.MAX_SAFE_INTEGER); const pageSize = pagination(query.pageSize, 20, 100); const sortBy = query.sortBy ?? "transactionDate"; const sortOrder = query.sortOrder ?? "desc"; const where: Prisma.TransactionWhereInput = { deletedAt: null, userId, accountId: query.accountId, categoryId: query.categoryId, type: query.type, status: query.status, transactionDate: { gte: query.startDate ? new Date(query.startDate) : undefined, lte: query.endDate ? new Date(query.endDate) : undefined }, description: query.search ? { contains: query.search.trim(), mode: "insensitive" } : undefined, account: query.currency ? { currency: query.currency } : undefined }; const [records, total] = await this.prisma.$transaction([this.prisma.transaction.findMany({ orderBy: [{ [sortBy]: sortOrder }, { id: sortOrder }], select: transactionSelect, skip: (page - 1) * pageSize, take: pageSize, where }), this.prisma.transaction.count({ where })]); return { data: records.map(present), meta: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } }; }
  async findOne(userId: string, id: string): Promise<TransactionResponse> { const record = await this.prisma.transaction.findFirst({ select: transactionSelect, where: { deletedAt: null, id, userId } }); if (!record) throw this.notFound(); return present(record); }
  async update(userId: string, id: string, dto: UpdateTransactionDto): Promise<TransactionResponse> { if (dto.amount !== undefined) assertAmount(dto.amount); return this.prisma.$transaction(async transaction => { const previous = await transaction.transaction.findFirst({ where: { deletedAt: null, id, userId } }); if (!previous) throw this.notFound(); const accountId = dto.accountId ?? previous.accountId; const categoryId = dto.categoryId === undefined ? previous.categoryId : dto.categoryId; const type = dto.type ?? previous.type; const amount = dto.amount ? new Prisma.Decimal(dto.amount) : previous.amount; const status = dto.status ?? previous.status; await this.validateReferences(transaction, userId, accountId, categoryId, type); if (previous.status === "CONFIRMED") await applyBalanceDelta(transaction, previous.accountId, previous.type, previous.amount, true); const record = await transaction.transaction.update({ data: { accountId, amount, categoryId, description: dto.description?.trim(), merchantName: dto.merchantName, notes: dto.notes, status, transactionDate: dto.transactionDate ? new Date(dto.transactionDate) : undefined, type }, select: transactionSelect, where: { id } }); if (record.status === "CONFIRMED") await applyBalanceDelta(transaction, record.accountId, record.type, record.amount); return present(record); }); }
  async remove(userId: string, id: string): Promise<void> { await this.prisma.$transaction(async transaction => { const record = await transaction.transaction.findFirst({ where: { deletedAt: null, id, userId } }); if (!record) throw this.notFound(); if (record.status !== "CONFIRMED") throw new ConflictException({ code: "TRANSACTION_NOT_CONFIRMED", message: "Transaction cannot be removed" }); await applyBalanceDelta(transaction, record.accountId, record.type, record.amount, true); await transaction.transaction.update({ data: { deletedAt: new Date(), status: "DELETED" }, where: { id } }); }); await this.audit.record({ action: "transaction.delete", actorUserId: userId, entityId: id, entityType: "transaction", eventType: "ENTITY_DELETED", riskLevel: "MEDIUM", userId }); }
  private async validateReferences(transaction: DatabaseTransaction, userId: string, accountId: string, categoryId: string | null | undefined, type: "INCOME" | "EXPENSE" | "ADJUSTMENT" | "TRANSFER_IN" | "TRANSFER_OUT"): Promise<void> { const account = await transaction.account.findFirst({ where: { deletedAt: null, id: accountId, status: "ACTIVE", userId } }); if (!account) throw new NotFoundException({ code: "ACCOUNT_NOT_FOUND", message: "Account not found" }); if (!categoryId) return; const category = await transaction.category.findFirst({ where: { deletedAt: null, id: categoryId, OR: [{ userId }, { isDefault: true, userId: null }] } }); if (!category) throw new NotFoundException({ code: "CATEGORY_NOT_FOUND", message: "Category not found" }); const expectedType = type === "INCOME" ? "INCOME" : "EXPENSE"; if (category.type !== "BOTH" && category.type !== expectedType) throw new ConflictException({ code: "CATEGORY_INCOMPATIBLE", message: "Category is incompatible with transaction type" }); }
  private notFound(): NotFoundException { return new NotFoundException({ code: "TRANSACTION_NOT_FOUND", message: "Transaction not found" }); }
}
