import { ConflictException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { AuditService } from "../audit/audit.service.js";
import { PrismaService } from "../prisma/prisma.service.js";
import type { CreateTransactionDto, UpdateTransactionDto } from "./dto/transaction.dto.js";
const select = { id:true, accountId:true, categoryId:true, type:true, status:true, description:true, amount:true, transactionDate:true, postedAt:true, merchantName:true, notes:true, createdAt:true, updatedAt:true } as const;
const present=(x:any)=>({...x,amount:x.amount.toString()});
@Injectable() export class TransactionsService {
 constructor(@Inject(PrismaService) private readonly prisma:PrismaService,@Inject(AuditService) private readonly audit:AuditService){}
 async create(userId:string,dto:CreateTransactionDto){ return this.prisma.$transaction(async tx=>{ await this.valid(tx,userId,dto.accountId,dto.categoryId,dto.type); const row=await tx.transaction.create({data:{...dto,description:dto.description.trim(),transactionDate:new Date(dto.transactionDate),userId,source:"MANUAL",amount:new Prisma.Decimal(dto.amount),status:dto.status??"CONFIRMED"},select}); if(row.status==="CONFIRMED") await this.apply(tx,row.accountId,row.type,row.amount); await this.audit.record({action:"transaction.create",actorUserId:userId,entityId:row.id,entityType:"transaction",eventType:"ENTITY_CREATED",riskLevel:"LOW",userId}); return present(row); }); }
 async list(userId:string){ const rows=await this.prisma.transaction.findMany({where:{userId,deletedAt:null},select,orderBy:[{transactionDate:"desc"},{id:"desc"}]}); return {data:rows.map(present),meta:{page:1,pageSize:20,total:rows.length,totalPages:1}}; }
 async findOne(userId:string,id:string){const row=await this.prisma.transaction.findFirst({where:{id,userId,deletedAt:null},select});if(!row)throw this.no();return present(row);}
 async remove(userId:string,id:string){await this.prisma.$transaction(async tx=>{const row=await tx.transaction.findFirst({where:{id,userId,deletedAt:null}});if(!row)throw this.no();if(row.status!=="CONFIRMED")throw new ConflictException({code:"TRANSACTION_NOT_CONFIRMED",message:"Transaction cannot be removed"});await this.apply(tx,row.accountId,row.type,row.amount,true);await tx.transaction.update({where:{id},data:{status:"DELETED",deletedAt:new Date()}});});await this.audit.record({action:"transaction.delete",actorUserId:userId,entityId:id,entityType:"transaction",eventType:"ENTITY_DELETED",riskLevel:"MEDIUM",userId});}
 async update(userId:string,id:string,dto:UpdateTransactionDto){return this.prisma.$transaction(async tx=>{const old=await tx.transaction.findFirst({where:{id,userId,deletedAt:null}});if(!old)throw this.no();const accountId=dto.accountId??old.accountId, type=dto.type??old.type, categoryId=dto.categoryId===undefined?old.categoryId:dto.categoryId, amount=dto.amount?new Prisma.Decimal(dto.amount):old.amount,status=dto.status??old.status;await this.valid(tx,userId,accountId,categoryId,type);if(old.status==="CONFIRMED")await this.apply(tx,old.accountId,old.type,old.amount,true);const row=await tx.transaction.update({where:{id},data:{...dto,accountId,categoryId,amount,status,transactionDate:dto.transactionDate?new Date(dto.transactionDate):undefined},select});if(row.status==="CONFIRMED")await this.apply(tx,row.accountId,row.type,row.amount);return present(row);});}
 private async valid(tx:any,userId:string,accountId:string,categoryId:string|undefined|null,type:string){const a=await tx.account.findFirst({where:{id:accountId,userId,deletedAt:null,status:"ACTIVE"}});if(!a)throw new NotFoundException({code:"ACCOUNT_NOT_FOUND",message:"Account not found"});if(categoryId){const c=await tx.category.findFirst({where:{id:categoryId,deletedAt:null,OR:[{userId},{userId:null,isDefault:true}]}});if(!c)throw new NotFoundException({code:"CATEGORY_NOT_FOUND",message:"Category not found"});if(c.type!=="BOTH"&&c.type!==type.toLowerCase())throw new ConflictException({code:"CATEGORY_INCOMPATIBLE",message:"Category is incompatible with transaction type"});}}
 private async apply(tx:any,id:string,type:string,amount:any,reverse=false){const increase=(type==="INCOME"||type==="ADJUSTMENT")!==reverse;await tx.account.update({where:{id},data:{currentBalance:increase?{increment:amount}:{decrement:amount}}});}
 private no(){return new NotFoundException({code:"TRANSACTION_NOT_FOUND",message:"Transaction not found"});}
}
