import { ConflictException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma } from "@prisma/client";

import { AuditService } from "../audit/audit.service.js";
import { applyBalanceDelta, serializeDecimal } from "../financial/money.js";
import { PrismaService } from "../prisma/prisma.service.js";
import type { CreateTransferDto } from "./dto/create-transfer.dto.js";

const transferSelect = { id: true, fromAccountId: true, toAccountId: true, amount: true, transferDate: true, description: true, status: true, createdAt: true, updatedAt: true } satisfies Prisma.TransferSelect;
type TransferRecord = Prisma.TransferGetPayload<{ select: typeof transferSelect }>;
export type TransferResponse = Omit<TransferRecord, "amount"> & { amount: string };
function present(record: TransferRecord): TransferResponse { return { ...record, amount: serializeDecimal(record.amount) }; }

@Injectable()
export class TransfersService {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService, @Inject(AuditService) private readonly audit: AuditService) {}
  async create(userId: string, dto: CreateTransferDto): Promise<TransferResponse> { if (dto.fromAccountId === dto.toAccountId) throw new ConflictException({ code: "TRANSFER_SAME_ACCOUNT", message: "Transfer accounts must differ" }); const result = await this.prisma.$transaction(async transaction => { const accounts = await transaction.account.findMany({ where: { deletedAt: null, id: { in: [dto.fromAccountId, dto.toAccountId] }, status: "ACTIVE", userId } }); if (accounts.length !== 2) throw new NotFoundException({ code: "ACCOUNT_NOT_FOUND", message: "Account not found" }); const [fromAccount, toAccount] = accounts; if (!fromAccount || !toAccount || fromAccount.currency !== toAccount.currency) throw new ConflictException({ code: "TRANSFER_CURRENCY_MISMATCH", message: "Accounts must use the same currency" }); const amount = new Prisma.Decimal(dto.amount); const transfer = await transaction.transfer.create({ data: { amount, description: dto.description?.trim(), fromAccountId: dto.fromAccountId, toAccountId: dto.toAccountId, transferDate: new Date(dto.transferDate), userId }, select: transferSelect }); await transaction.transaction.createMany({ data: [{ accountId: dto.fromAccountId, amount, description: dto.description?.trim() ?? "Transfer", source: "SYSTEM", status: "CONFIRMED", transactionDate: new Date(dto.transferDate), transferId: transfer.id, type: "TRANSFER_OUT", userId }, { accountId: dto.toAccountId, amount, description: dto.description?.trim() ?? "Transfer", source: "SYSTEM", status: "CONFIRMED", transactionDate: new Date(dto.transferDate), transferId: transfer.id, type: "TRANSFER_IN", userId }] }); await applyBalanceDelta(transaction, dto.fromAccountId, "TRANSFER_OUT", amount); await applyBalanceDelta(transaction, dto.toAccountId, "TRANSFER_IN", amount); return present(transfer); }); await this.audit.record({ action: "transfer.create", actorUserId: userId, entityId: result.id, entityType: "transfer", eventType: "ENTITY_CREATED", riskLevel: "MEDIUM", userId }); return result; }
  async list(userId: string): Promise<TransferResponse[]> { const records = await this.prisma.transfer.findMany({ orderBy: [{ transferDate: "desc" }, { id: "desc" }], select: transferSelect, where: { deletedAt: null, userId } }); return records.map(present); }
  async findOne(userId: string, id: string): Promise<TransferResponse> { const record = await this.prisma.transfer.findFirst({ select: transferSelect, where: { deletedAt: null, id, userId } }); if (!record) throw this.notFound(); return present(record); }
  async remove(userId: string, id: string): Promise<void> { await this.prisma.$transaction(async transaction => { const transfer = await transaction.transfer.findFirst({ where: { deletedAt: null, id, userId } }); if (!transfer) throw this.notFound(); await applyBalanceDelta(transaction, transfer.fromAccountId, "TRANSFER_OUT", transfer.amount, true); await applyBalanceDelta(transaction, transfer.toAccountId, "TRANSFER_IN", transfer.amount, true); await transaction.transaction.updateMany({ data: { deletedAt: new Date(), status: "DELETED" }, where: { deletedAt: null, transferId: id } }); await transaction.transfer.update({ data: { deletedAt: new Date(), status: "DELETED" }, where: { id } }); }); await this.audit.record({ action: "transfer.delete", actorUserId: userId, entityId: id, entityType: "transfer", eventType: "ENTITY_DELETED", riskLevel: "MEDIUM", userId }); }
  private notFound(): NotFoundException { return new NotFoundException({ code: "TRANSFER_NOT_FOUND", message: "Transfer not found" }); }
}
