/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-call */
import { AuditService } from "../audit/audit.service.js";
import { PrismaService } from "../prisma/prisma.service.js";
import { CategoriesService } from "./categories.service.js";
const userId = "11111111-1111-4111-8111-111111111111"; const otherUserId = "22222222-2222-4222-8222-222222222222"; const id = "33333333-3333-4333-8333-333333333333";
const category = (owner: string | null = userId) => ({ color: null, createdAt: new Date(), deletedAt: null, icon: null, id, isDefault: owner === null, isEssential: false, name: "Food", parentId: null, sortOrder: 0, status: "ACTIVE", type: "EXPENSE", updatedAt: new Date(), userId: owner });
function harness() { const rows = [category(), { ...category(null), id: "44444444-4444-4444-8444-444444444444", name: "Global" }]; const prisma: any = { category: { create: jest.fn(({ data }) => Promise.resolve({ ...category(data.userId), ...data, id: "55555555-5555-4555-8555-555555555555" })), findFirst: jest.fn(({ where }) => Promise.resolve(rows.find((row) => row.id === where.id && !row.deletedAt && (where.userId === undefined || row.userId === where.userId)) ?? null)), findMany: jest.fn(() => Promise.resolve(rows)), update: jest.fn(({ data, where }) => { const row = rows.find((item) => item.id === where.id)!; Object.assign(row, data); return Promise.resolve(row); }), count: jest.fn().mockResolvedValue(0) }, transaction: { count: jest.fn().mockResolvedValue(0) }, budgetCategoryLimit: { count: jest.fn().mockResolvedValue(0) }, recurringTransaction: { count: jest.fn().mockResolvedValue(0) }, importItem: { count: jest.fn().mockResolvedValue(0) }, monthlyCategorySummary: { count: jest.fn().mockResolvedValue(0) }, auditLog: { create: jest.fn().mockResolvedValue({}) } }; return { prisma, rows, service: new CategoriesService(prisma as PrismaService, new AuditService(prisma as PrismaService)) }; }
describe("CategoriesService", () => {
  it("creates a personal category without accepting an owner from the DTO", async () => { const { service, prisma } = harness(); await service.create(userId, { name: "Home", type: "EXPENSE" as any }); expect(prisma.category.create.mock.calls[0][0].data.userId).toBe(userId); });
  it("lists personal and global default categories", async () => { const { service } = harness(); await expect(service.list(userId)).resolves.toHaveLength(2); });
  it("blocks IDOR and global-category modification", async () => { const { service } = harness(); await expect(service.update(otherUserId, id, { name: "No" })).rejects.toMatchObject({ status: 404 }); await expect(service.update(userId, "44444444-4444-4444-8444-444444444444", { name: "No" })).rejects.toMatchObject({ status: 404 }); });
  it("soft-deletes an unused personal category", async () => { const { service, rows } = harness(); await service.remove(userId, id); expect(rows[0]!.status).toBe("DELETED"); });
  it("rejects deletion of a category with linked transactions", async () => { const { service, prisma } = harness(); prisma.transaction.count.mockResolvedValueOnce(1); await expect(service.remove(userId, id)).rejects.toMatchObject({ status: 409 }); });
});
