import { Inject, Injectable } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { DashboardService } from "../dashboard/dashboard.service.js";
import { FinancialHealthService } from "../financial-health/financial-health.service.js";
import { PrismaService } from "../prisma/prisma.service.js";
import { ReportsService } from "../reports/reports.service.js";
import type { InsightDetectionContext } from "./detectors/insight-detector.interface.js";

@Injectable()
export class InsightContextService {
  constructor(@Inject(DashboardService) private readonly dashboard: DashboardService, @Inject(FinancialHealthService) private readonly health: FinancialHealthService, @Inject(ReportsService) private readonly reports: ReportsService, @Inject(PrismaService) private readonly prisma: PrismaService) {}

  async currencies(userId:string,selected?:string):Promise<readonly string[]>{if(selected)return [selected.toUpperCase()];const rows=await this.prisma.account.findMany({where:{userId,deletedAt:null,status:{not:"DELETED"}},select:{currency:true},distinct:["currency"],orderBy:{currency:"asc"}});return rows.map(row=>row.currency);}

  async build(userId:string,currency:string,period:{start:Date;end:Date}):Promise<InsightDetectionContext>{
    const duration=period.end.getTime()-period.start.getTime()+1;const previousPeriod={start:new Date(period.start.getTime()-duration),end:new Date(period.start.getTime()-1)};const query={currency,startDate:period.start.toISOString(),endDate:period.end.toISOString()};const previousQuery={currency,startDate:previousPeriod.start.toISOString(),endDate:previousPeriod.end.toISOString()};
    const [overview,budgets,goals,health,netWorth,categories,previousCategories,recurring]=await Promise.all([this.dashboard.overview(userId,query),this.dashboard.budgets(userId,query),this.prisma.goal.findMany({where:{userId,currency},select:{id:true,type:true,currency:true,currentAmount:true,targetAmount:true,targetDate:true,status:true,deletedAt:true,emergencyFundPlan:{select:{id:true}}}}),this.health.calculate(userId,query),this.reports.netWorth(userId,query),this.dashboard.categories(userId,query),this.dashboard.categories(userId,previousQuery),this.dashboard.recurring(userId,query)]);
    const current={income:new Prisma.Decimal(overview.income),expenses:new Prisma.Decimal(overview.expenses),net:new Prisma.Decimal(overview.netCashFlow),hasData:overview.transactionsCount>0};const prior={income:new Prisma.Decimal(overview.previousPeriod.income),expenses:new Prisma.Decimal(overview.previousPeriod.expenses),net:new Prisma.Decimal(overview.previousPeriod.net),hasData:overview.previousPeriod.income!=="0"||overview.previousPeriod.expenses!=="0"};const healthOne="data" in health?health.data.find(item=>item.period.currency===currency)??null:health;const worth=netWorth.data.find(item=>item.currency===currency)??null;
    return {userId,currency,period,previousPeriod,budgets:budgets.data.flatMap(budget=>budget.categoryLimits.map(limit=>({budgetId:budget.id,categoryId:limit.categoryId,currency:budget.currency,limit:new Prisma.Decimal(limit.limitAmount),spent:new Prisma.Decimal(limit.spentAmount),active:budget.status==="ACTIVE"}))),cashFlow:current,previousCashFlow:prior,goals:goals.map(goal=>({id:goal.id,type:goal.type,currency:goal.currency,current:goal.currentAmount,target:goal.targetAmount,targetDate:goal.targetDate,status:goal.status,deleted:goal.deletedAt!==null,planId:goal.emergencyFundPlan?.id??null})),financialHealth:healthOne?{score:healthOne.score,classification:healthOne.classification,dataQuality:healthOne.dataQuality.status,components:healthOne.components.map(component=>({code:component.code,score:component.score,available:component.available}))}:null,netWorth:worth?{current:new Prisma.Decimal(worth.currentNetWorth),initial:new Prisma.Decimal(worth.estimatedInitialNetWorth),change:new Prisma.Decimal(worth.netChange),accounts:worth.accounts.map(account=>({id:account.accountId,type:account.accountType,balance:new Prisma.Decimal(account.balance),participation:account.participationPercentage===null?null:new Prisma.Decimal(account.participationPercentage)})),hasData:worth.accounts.length>0}:null,categories:categories.data.filter(item=>item.type==="EXPENSE").map(item=>({categoryId:item.categoryId,amount:new Prisma.Decimal(item.amount),percentage:item.percentage===null?null:new Prisma.Decimal(item.percentage)})),previousCategories:previousCategories.data.filter(item=>item.type==="EXPENSE").map(item=>({categoryId:item.categoryId,amount:new Prisma.Decimal(item.amount),percentage:item.percentage===null?null:new Prisma.Decimal(item.percentage)})),recurring:recurring.data.map(item=>({id:item.id,currency:item.currency,type:item.type,kind:item.recurrenceKind,amount:new Prisma.Decimal(item.amount),nextOccurrence:item.nextOccurrenceDate,active:true,deleted:false})),generatedAt:new Date()};
  }
}
