import { Inject, Injectable } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { DashboardService } from "../dashboard/dashboard.service.js";
import { FinancialHealthService } from "../financial-health/financial-health.service.js";
import { PrismaService } from "../prisma/prisma.service.js";
import type { InsightDetectionContext } from "./detectors/insight-detector.interface.js";

@Injectable()
export class InsightContextService {
  constructor(@Inject(DashboardService) private readonly dashboard: DashboardService, @Inject(FinancialHealthService) private readonly health: FinancialHealthService, @Inject(PrismaService) private readonly prisma: PrismaService) {}
  async currencies(userId:string,selected?:string):Promise<readonly string[]>{if(selected)return [selected.toUpperCase()];const rows=await this.prisma.account.findMany({where:{userId,deletedAt:null,status:{not:"DELETED"}},select:{currency:true},distinct:["currency"],orderBy:{currency:"asc"}});return rows.map(row=>row.currency);}
  async build(userId:string,currency:string,period:{start:Date;end:Date}):Promise<InsightDetectionContext>{const duration=period.end.getTime()-period.start.getTime()+1;const previousPeriod={start:new Date(period.start.getTime()-duration),end:new Date(period.start.getTime()-1)};const query={currency,startDate:period.start.toISOString(),endDate:period.end.toISOString()};const [overview,budgets,goals,health]=await Promise.all([this.dashboard.overview(userId,query),this.dashboard.budgets(userId,query),this.prisma.goal.findMany({where:{userId,currency},select:{id:true,type:true,currency:true,currentAmount:true,targetAmount:true,targetDate:true,status:true,deletedAt:true,emergencyFundPlan:{select:{id:true}}}}),this.health.calculate(userId,query)]);const current={income:new Prisma.Decimal(overview.income),expenses:new Prisma.Decimal(overview.expenses),net:new Prisma.Decimal(overview.netCashFlow),hasData:overview.transactionsCount>0};const prior={income:new Prisma.Decimal(overview.previousPeriod.income),expenses:new Prisma.Decimal(overview.previousPeriod.expenses),net:new Prisma.Decimal(overview.previousPeriod.net),hasData:overview.previousPeriod.income!=="0"||overview.previousPeriod.expenses!=="0"};const healthOne="data" in health?health.data.find(item=>item.period.currency===currency)??null:health;return {userId,currency,period,previousPeriod,budgets:budgets.data.flatMap(budget=>budget.categoryLimits.map(limit=>({budgetId:budget.id,categoryId:limit.categoryId,currency:budget.currency,limit:new Prisma.Decimal(limit.limitAmount),spent:new Prisma.Decimal(limit.spentAmount),active:budget.status==="ACTIVE"}))),cashFlow:current,previousCashFlow:prior,goals:goals.map(goal=>({id:goal.id,type:goal.type,currency:goal.currency,current:goal.currentAmount,target:goal.targetAmount,targetDate:goal.targetDate,status:goal.status,deleted:goal.deletedAt!==null,planId:goal.emergencyFundPlan?.id??null})),financialHealth:healthOne?{score:healthOne.score,classification:healthOne.classification,dataQuality:healthOne.dataQuality.status,components:healthOne.components.map(component=>({code:component.code,score:component.score,available:component.available}))}:null,generatedAt:new Date()};}
}
