import { BadRequestException, ConflictException, NotFoundException } from "@nestjs/common";
import { GoalContributionType, GoalStatus, Prisma, type Goal } from "@prisma/client";
import { GoalsService } from "./goals.service.js";
import { GoalContributionTypeDto, GoalSortByDto, GoalStatusDto, SortOrderDto } from "./dto/goal.dto.js";
import { createAuthenticatedUser, createGoal, createGoalContribution, testDecimal, testUuid } from "../../test-utils/financial-fixtures.js";
import { createFinancialPrismaMock } from "../../test-utils/financial-prisma.mock.js";

describe("GoalsService", () => {
  const user = createAuthenticatedUser(); let prisma = createFinancialPrismaMock(); const audit = { record: jest.fn<Promise<void>, [never]>() };
  let service: GoalsService;
  beforeEach(() => { prisma = createFinancialPrismaMock(); audit.record.mockResolvedValue(undefined); service = new GoalsService(prisma, audit); });
  const goal = (overrides: Partial<Goal> = {}) => createGoal({ id: testUuid(2), userId: user.id, ...overrides });

  it("creates an isolated goal with decimal amounts", async () => {
    prisma.goal.create.mockResolvedValue(goal()); const result = await service.create(user.id, { name: " Reserve ", targetAmount: "1000.1250" });
    expect(prisma.goal.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ userId: user.id, name: "Reserve", targetAmount: expect.any(Prisma.Decimal) }) })); expect(result.targetAmount).toBe("1000"); expect(result.currentAmount).toBe("0");
  });
  it.each(["0", "-1", "1.00001", "1e3", "NaN", "Infinity"])("rejects invalid target amount %s", async value => { await expect(service.create(user.id, { name: "Reserve", targetAmount: value })).rejects.toBeInstanceOf(BadRequestException); });
  it("lists only active, non-deleted user goals in one transaction", async () => {
    prisma.goal.findMany.mockResolvedValue([goal()]); prisma.goal.count.mockResolvedValue(1); const result = await service.list(user.id, { page: 2, pageSize: 10, status: GoalStatusDto.ACTIVE, sortBy: GoalSortByDto.CREATED_AT, sortOrder: SortOrderDto.DESC });
    expect(prisma.transactionCalls).toBe(1); expect(prisma.goal.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ userId: user.id, deletedAt: null, status: "ACTIVE" }), skip: 10, take: 10, orderBy: [{ createdAt: "desc" }, { id: "desc" }] })); expect(result.meta).toEqual({ page: 2, pageSize: 10, total: 1, totalPages: 1 });
  });
  it("returns goal details with owned non-deleted contributions", async () => { prisma.goal.findFirst.mockResolvedValue(goal()); prisma.goalContribution.findMany.mockResolvedValue([createGoalContribution({ goalId: testUuid(2), userId: user.id })]); const result = await service.findOne(user.id, testUuid(2)); expect(result.contributions).toHaveLength(1); expect(prisma.goal.findFirst).toHaveBeenCalledWith({ where: { id: testUuid(2), userId: user.id, deletedAt: null } }); });
  it("hides missing, deleted, and another user goals", async () => { prisma.goal.findFirst.mockResolvedValue(null); await expect(service.findOne(user.id, testUuid(2))).rejects.toBeInstanceOf(NotFoundException); });
  it("updates a goal without allowing invalid transitions", async () => { prisma.goal.findFirst.mockResolvedValue(goal({ status: GoalStatus.COMPLETED })); await expect(service.update(user.id, testUuid(2), { status: GoalStatusDto.ACTIVE })).rejects.toBeInstanceOf(ConflictException); });
  it("soft deletes the goal", async () => { prisma.goal.findFirst.mockResolvedValue(goal()); prisma.goal.update.mockResolvedValue(goal({ status: GoalStatus.DELETED, deletedAt: new Date() })); await service.remove(user.id, testUuid(2)); expect(prisma.goal.update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: "DELETED", deletedAt: expect.any(Date) }) })); });
  it("creates a contribution and updates the amount atomically", async () => { const initial = goal({ currentAmount: testDecimal("40") }); prisma.goal.findFirst.mockResolvedValue(initial); prisma.goalContribution.create.mockResolvedValue(createGoalContribution({ goalId: initial.id, userId: user.id, amount: testDecimal("10") })); prisma.goal.update.mockResolvedValue(initial); const result = await service.addContribution(user.id, initial.id, { type: GoalContributionTypeDto.CONTRIBUTION, amount: "10.0000", contributionDate: "2026-01-01" }); expect(prisma.transactionCalls).toBe(1); expect(prisma.goal.update).toHaveBeenCalledWith(expect.objectContaining({ data: { currentAmount: testDecimal("50") } })); expect(result.amount).toBe("10"); });
  it("does not allow withdrawals below zero", async () => { const initial = goal({ currentAmount: testDecimal("5") }); prisma.goal.findFirst.mockResolvedValue(initial); await expect(service.addContribution(user.id, initial.id, { type: GoalContributionTypeDto.WITHDRAWAL, amount: "10", contributionDate: "2026-01-01" })).rejects.toBeInstanceOf(ConflictException); });
  it("rejects contributions to a paused goal", async () => { prisma.goal.findFirst.mockResolvedValue(goal({ status: GoalStatus.PAUSED })); await expect(service.addContribution(user.id, testUuid(2), { type: GoalContributionTypeDto.CONTRIBUTION, amount: "1", contributionDate: "2026-01-01" })).rejects.toBeInstanceOf(ConflictException); });
  it("lists contributions only after verifying goal ownership", async () => { prisma.goal.findFirst.mockResolvedValue(goal()); prisma.goalContribution.findMany.mockResolvedValue([]); await service.listContributions(user.id, testUuid(2)); expect(prisma.goalContribution.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { userId: user.id, goalId: testUuid(2), deletedAt: null } })); });
  it("soft deletes a contribution and reverses its contribution", async () => { const initial = goal({ currentAmount: testDecimal("100") }); const contribution = createGoalContribution({ id: testUuid(3), goalId: initial.id, userId: user.id, type: GoalContributionType.CONTRIBUTION, amount: testDecimal("40") }); prisma.goal.findFirst.mockResolvedValue(initial); prisma.goalContribution.findFirst.mockResolvedValue(contribution); prisma.goalContribution.update.mockResolvedValue(contribution); prisma.goal.update.mockResolvedValue(initial); await service.removeContribution(user.id, initial.id, contribution.id); expect(prisma.goalContribution.update).toHaveBeenCalledWith(expect.objectContaining({ data: { deletedAt: expect.any(Date) } })); expect(prisma.goal.update).toHaveBeenCalledWith(expect.objectContaining({ data: { currentAmount: testDecimal("60") } })); });
});
